In [1]:
import pandas as pd  # Pandas untuk manipulasi dan analisis data
pd.options.mode.chained_assignment = None  # Menonaktifkan peringatan chaining
import numpy as np  # NumPy untuk komputasi numerik
seed = 0
np.random.seed(seed)  # Mengatur seed untuk reproduktibilitas
import matplotlib.pyplot as plt  # Matplotlib untuk visualisasi data
import seaborn as sns  # Seaborn untuk visualisasi data statistik, mengatur gaya visualisasi

import datetime as dt  # Manipulasi data waktu dan tanggal
import re  # Modul untuk bekerja dengan ekspresi reguler
import string  # Berisi konstanta string, seperti tanda baca
from nltk.tokenize import word_tokenize  # Tokenisasi teks
from nltk.corpus import stopwords  # Daftar kata-kata berhenti dalam teks

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory  # Stemming (penghilangan imbuhan kata) dalam bahasa Indonesia
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory  # Menghapus kata-kata berhenti dalam bahasa Indonesia

from wordcloud import WordCloud  # Membuat visualisasi berbentuk awan kata (word cloud) dari teks

In [2]:
import nltk  # Import pustaka NLTK (Natural Language Toolkit).
nltk.download('punkt')  # Mengunduh dataset yang diperlukan untuk tokenisasi teks.
nltk.download('stopwords')  # Mengunduh dataset yang berisi daftar kata-kata berhenti (stop words) dalam berbagai bahasa.

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
df = pd.read_csv('ruangguru_review.csv')

In [4]:
df

                                                 content
0      semuanya yg ada di ruang guru sangat bagus tet...
1      saya lagi nonton video pembelajaran nih, diman...
2      bagus banget nih buat belajar, untuk sekarang ...
3      Overall semuanya tampak bagus, tapi tolong dev...
4      ruangguru benar² menjadi ruang yang menyenangk...
...                                                  ...
21586  mendapatkan sebuah pelajaran yang lebih efekti...
21587  Aplikasi ini membuat saya semakin ngerti tenta...
21588  yey bisa belajar lagi asah otak lagi guys tapi...
21589  aplikasi ini bagus sangat ber prestasi da sela...
21590  Ruangguru sangat bermanfaat sekali untuk saya ...

[21591 rows x 1 columns]

In [5]:
def cleaningText(text):
    text = re.sub(r'@[A-Za-z0-9]+', '', text) # remove mentions
    text = re.sub(r'#[A-Za-z0-9]+', '', text) # remove hashtag
    text = re.sub(r'RT[\s]', '', text) # remove RT
    text = re.sub(r"http\S+", '', text) # remove link
    text = re.sub(r'[0-9]+', '', text) # remove numbers
    text = re.sub(r'[^\w\s]', '', text) # remove numbers


    text = text.replace('\n', ' ') # replace new line into space
    text = text.translate(str.maketrans('', '', string.punctuation)) # remove all punctuations
    text = text.strip(' ') # remove characters space from both left and right text
    return text

def casefoldingText(text): # Converting all the characters in a text into lower case
    text = text.lower()
    return text

def tokenizingText(text): # Tokenizing or splitting a string, text into a list of tokens
    text = word_tokenize(text)
    return text

def filteringText(text): # Remove stopwors in a text
    listStopwords = set(stopwords.words('indonesian'))
    listStopwords1 = set(stopwords.words('english'))
    listStopwords.update(listStopwords1)
    listStopwords.update(['iya','yaa','gak','nya','na','sih','ku',"di","ga","ya","gaa","loh","kah","woi","woii","woy"])
    filtered = []
    for txt in text:
        if txt not in listStopwords:
            filtered.append(txt)
    text = filtered
    return text

def stemmingText(text): # Reducing a word to its word stem that affixes to suffixes and prefixes or to the roots of words
    # Membuat objek stemmer
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()

    # Memecah teks menjadi daftar kata
    words = text.split()

    # Menerapkan stemming pada setiap kata dalam daftar
    stemmed_words = [stemmer.stem(word) for word in words]

    # Menggabungkan kata-kata yang telah distem
    stemmed_text = ' '.join(stemmed_words)

    return stemmed_text

    return stemmed_text
def toSentence(list_words): # Convert list of words into sentence
    sentence = ' '.join(word for word in list_words)
    return sentence

In [6]:
slangwords = {"@": "di", "abis": "habis", "wtb": "beli", "masi": "masih", "wts": "jual", "wtt": "tukar", "bgt": "banget", "maks": "maksimal", "plisss": "tolong", "bgttt": "banget", "indo": "indonesia", "bgtt": "banget", "ad": "ada", "rv": "redvelvet", "plis": "tolong", "pls": "tolong", "cr": "sumber", "cod": "bayar ditempat", "adlh": "adalah", "afaik": "as far as i know", "ahaha": "haha", "aj": "saja", "ajep-ajep": "dunia gemerlap", "ak": "saya", "akika": "aku", "akkoh": "aku", "akuwh": "aku", "alay": "norak", "alow": "halo", "ambilin": "ambilkan", "ancur": "hancur", "anjrit": "anjing", "anter": "antar", "ap2": "apa-apa", "apasih": "apa sih", "apes": "sial", "aps": "apa", "aq": "saya", "aquwh": "aku", "asbun": "asal bunyi", "aseekk": "asyik", "asekk": "asyik", "asem": "asam", "aspal": "asli tetapi palsu", "astul": "asal tulis", "ato": "atau", "au ah": "tidak mau tahu", "awak": "saya", "ay": "sayang", "ayank": "sayang", "b4": "sebelum", "bakalan": "akan", "bandes": "bantuan desa", "bangedh": "banget", "banpol": "bantuan polisi", "banpur": "bantuan tempur", "basbang": "basi", "bcanda": "bercanda", "bdg": "bandung", "begajulan": "nakal", "beliin": "belikan", "bencong": "banci", "bentar": "sebentar", "ber3": "bertiga", "beresin": "membereskan", "bete": "bosan", "beud": "banget", "bg": "abang", "bgmn": "bagaimana", "bgt": "banget", "bijimane": "bagaimana", "bintal": "bimbingan mental", "bkl": "akan", "bknnya": "bukannya", "blegug": "bodoh", "blh": "boleh", "bln": "bulan", "blum": "belum", "bnci": "benci", "bnran": "yang benar", "bodor": "lucu", "bokap": "ayah", "boker": "buang air besar", "bokis": "bohong", "boljug": "boleh juga", "bonek": "bocah nekat", "boyeh": "boleh", "br": "baru", "brg": "bareng", "bro": "saudara laki-laki", "bru": "baru", "bs": "bisa", "bsen": "bosan", "bt": "buat", "btw": "ngomong-ngomong", "buaya": "tidak setia", "bubbu": "tidur", "bubu": "tidur", "bumil": "ibu hamil", "bw": "bawa", "bwt": "buat", "byk": "banyak", "byrin": "bayarkan", "cabal": "sabar", "cadas": "keren", "calo": "makelar", "can": "belum", "capcus": "pergi", "caper": "cari perhatian", "ce": "cewek", "cekal": "cegah tangkal", "cemen": "penakut", "cengengesan": "tertawa", "cepet": "cepat", "cew": "cewek", "chuyunk": "sayang", "cimeng": "ganja", "cipika cipiki": "cium pipi kanan cium pipi kiri", "ciyh": "sih", "ckepp": "cakep", "ckp": "cakep", "cmiiw": "correct me if i'm wrong", "cmpur": "campur", "cong": "banci", "conlok": "cinta lokasi", "cowwyy": "maaf", "cp": "siapa", "cpe": "capek", "cppe": "capek", "cucok": "cocok", "cuex": "cuek", "cumi": "Cuma miscall", "cups": "culun", "curanmor": "pencurian kendaraan bermotor", "curcol": "curahan hati colongan", "cwek": "cewek", "cyin": "cinta", "d": "di", "dah": "deh", "dapet": "dapat", "de": "adik", "dek": "adik", "demen": "suka", "deyh": "deh", "dgn": "dengan", "diancurin": "dihancurkan", "dimaafin": "dimaafkan", "dimintak": "diminta", "disono": "di sana", "dket": "dekat", "dkk": "dan kawan-kawan", "dll": "dan lain-lain", "dlu": "dulu", "dngn": "dengan", "dodol": "bodoh", "doku": "uang", "dongs": "dong", "dpt": "dapat", "dri": "dari", "drmn": "darimana", "drtd": "dari tadi", "dst": "dan seterusnya", "dtg": "datang", "duh": "aduh", "duren": "durian", "ed": "edisi", "egp": "emang gue pikirin", "eke": "aku", "elu": "kamu", "emangnya": "memangnya", "emng": "memang", "endak": "tidak", "enggak": "tidak", "envy": "iri", "ex": "mantan", "fax": "facsimile", "fifo": "first in first out", "folbek": "follow back", "fyi": "sebagai informasi", "gaada": "tidak ada uang", "gag": "tidak", "gaje": "tidak jelas", "gak papa": "tidak apa-apa", "gan": "juragan", "gaptek": "gagap teknologi", "gatek": "gagap teknologi", "gawe": "kerja", "gbs": "tidak bisa", "gebetan": "orang yang disuka", "geje": "tidak jelas", "gepeng": "gelandangan dan pengemis", "ghiy": "lagi", "gile": "gila", "gimana": "bagaimana", "gino": "gigi nongol", "githu": "gitu", "gj": "tidak jelas", "gmana": "bagaimana", "gn": "begini", "goblok": "bodoh", "golput": "golongan putih", "gowes": "mengayuh sepeda", "gpny": "tidak punya", "gr": "gede rasa", "gretongan": "gratisan", "gtau": "tidak tahu", "gua": "saya", "guoblok": "goblok", "gw": "saya", "ha": "tertawa", "haha": "tertawa", "hallow": "halo", "hankam": "pertahanan dan keamanan", "hehe": "he", "helo": "halo", "hey": "hai", "hlm": "halaman", "hny": "hanya", "hoax": "isu bohong", "hr": "hari", "hrus": "harus", "hubdar": "perhubungan darat", "huff": "mengeluh", "hum": "rumah", "humz": "rumah", "ilang": "hilang", "ilfil": "tidak suka", "imho": "in my humble opinion", "imoetz": "imut", "item": "hitam", "itungan": "hitungan", "iye": "iya", "ja": "saja", "jadiin": "jadi", "jaim": "jaga image", "jayus": "tidak lucu", "jdi": "jadi", "jem": "jam", "jga": "juga", "jgnkan": "jangankan", "jir": "anjing", "jln": "jalan", "jomblo": "tidak punya pacar", "jubir": "juru bicara", "jutek": "galak", "k": "ke", "kab": "kabupaten", "kabor": "kabur", "kacrut": "kacau", "kadiv": "kepala divisi", "kagak": "tidak", "kalo": "kalau", "kampret": "sialan", "kamtibmas": "keamanan dan ketertiban masyarakat", "kamuwh": "kamu", "kanwil": "kantor wilayah", "karna": "karena", "kasubbag": "kepala subbagian", "katrok": "kampungan", "kayanya": "kayaknya", "kbr": "kabar", "kdu": "harus", "kec": "kecamatan", "kejurnas": "kejuaraan nasional", "kekeuh": "keras kepala", "kel": "kelurahan", "kemaren": "kemarin", "kepengen": "mau", "kepingin": "mau", "kepsek": "kepala sekolah", "kesbang": "kesatuan bangsa", "kesra": "kesejahteraan rakyat", "ketrima": "diterima", "kgiatan": "kegiatan", "kibul": "bohong", "kimpoi": "kawin", "kl": "kalau", "klianz": "kalian", "kloter": "kelompok terbang", "klw": "kalau", "km": "kamu", "kmps": "kampus", "kmrn": "kemarin", "knal": "kenal", "knp": "kenapa", "kodya": "kota madya", "komdis": "komisi disiplin", "komsov": "komunis sovyet", "kongkow": "kumpul bareng teman-teman", "kopdar": "kopi darat", "korup": "korupsi", "kpn": "kapan", "krenz": "keren", "krm": "kirim", "kt": "kita", "ktmu": "ketemu", "ktr": "kantor", "kuper": "kurang pergaulan", "kw": "imitasi", "kyk": "seperti", "la": "lah", "lam": "salam", "lamp": "lampiran", "lanud": "landasan udara", "latgab": "latihan gabungan", "lebay": "berlebihan", "leh": "boleh", "lelet": "lambat", "lemot": "lambat", "lgi": "lagi", "lgsg": "langsung", "liat": "lihat", "litbang": "penelitian dan pengembangan", "lmyn": "lumayan", "lo": "kamu", "loe": "kamu", "lola": "lambat berfikir", "louph": "cinta", "low": "kalau", "lp": "lupa", "luber": "langsung, umum, bebas, dan rahasia", "luchuw": "lucu", "lum": "belum", "luthu": "lucu", "lwn": "lawan", "maacih": "terima kasih", "mabal": "bolos", "macem": "macam", "macih": "masih", "maem": "makan", "magabut": "makan gaji buta", "maho": "homo", "mak jang": "kaget", "maksain": "memaksa", "malem": "malam", "mam": "makan", "maneh": "kamu", "maniez": "manis", "mao": "mau", "masukin": "masukkan", "melu": "ikut", "mepet": "dekat sekali", "mgu": "minggu", "migas": "minyak dan gas bumi", "mikol": "minuman beralkohol", "miras": "minuman keras", "mlah": "malah", "mngkn": "mungkin", "mo": "mau", "mokad": "mati", "moso": "masa", "mpe": "sampai", "msk": "masuk", "mslh": "masalah", "mt": "makan teman", "mubes": "musyawarah besar", "mulu": "melulu", "mumpung": "selagi", "munas": "musyawarah nasional", "muntaber": "muntah dan berak", "musti": "mesti", "muupz": "maaf", "mw": "now watching", "n": "dan", "nanam": "menanam", "nanya": "bertanya", "napa": "kenapa", "napi": "narapidana", "napza": "narkotika, alkohol, psikotropika, dan zat adiktif ", "narkoba": "narkotika, psikotropika, dan obat terlarang", "nasgor": "nasi goreng", "nda": "tidak", "ndiri": "sendiri", "ne": "ini", "nekolin": "neokolonialisme", "nembak": "menyatakan cinta", "ngabuburit": "menunggu berbuka puasa", "ngaku": "mengaku", "ngambil": "mengambil", "nganggur": "tidak punya pekerjaan", "ngapah": "kenapa", "ngaret": "terlambat", "ngasih": "memberikan", "ngebandel": "berbuat bandel", "ngegosip": "bergosip", "ngeklaim": "mengklaim", "ngeksis": "menjadi eksis", "ngeles": "berkilah", "ngelidur": "menggigau", "ngerampok": "merampok", "ngga": "tidak", "ngibul": "berbohong", "ngiler": "mau", "ngiri": "iri", "ngisiin": "mengisikan", "ngmng": "bicara", "ngomong": "bicara", "ngubek2": "mencari-cari", "ngurus": "mengurus", "nie": "ini", "nih": "ini", "niyh": "nih", "nmr": "nomor", "nntn": "nonton", "nobar": "nonton bareng", "np": "now playing", "ntar": "nanti", "ntn": "nonton", "numpuk": "bertumpuk", "nutupin": "menutupi", "nyari": "mencari", "nyekar": "menyekar", "nyicil": "mencicil", "nyoblos": "mencoblos", "nyokap": "ibu", "ogah": "tidak mau", "ol": "online", "ongkir": "ongkos kirim", "oot": "out of topic", "org2": "orang-orang", "ortu": "orang tua", "otda": "otonomi daerah", "otw": "on the way, sedang di jalan", "pacal": "pacar", "pake": "pakai", "pala": "kepala", "pansus": "panitia khusus", "parpol": "partai politik", "pasutri": "pasangan suami istri", "pd": "pada", "pede": "percaya diri", "pelatnas": "pemusatan latihan nasional", "pemda": "pemerintah daerah", "pemkot": "pemerintah kota", "pemred": "pemimpin redaksi", "penjas": "pendidikan jasmani", "perda": "peraturan daerah", "perhatiin": "perhatikan", "pesenan": "pesanan", "pgang": "pegang", "pi": "tapi", "pilkada": "pemilihan kepala daerah", "pisan": "sangat", "pk": "penjahat kelamin", "plg": "paling", "pmrnth": "pemerintah", "polantas": "polisi lalu lintas", "ponpes": "pondok pesantren", "pp": "pulang pergi", "prg": "pergi", "prnh": "pernah", "psen": "pesan", "pst": "pasti", "pswt": "pesawat", "pw": "posisi nyaman", "qmu": "kamu", "rakor": "rapat koordinasi", "ranmor": "kendaraan bermotor", "re": "reply", "ref": "referensi", "rehab": "rehabilitasi", "rempong": "sulit", "repp": "balas", "restik": "reserse narkotika", "rhs": "rahasia", "rmh": "rumah", "ru": "baru", "ruko": "rumah toko", "rusunawa": "rumah susun sewa", "ruz": "terus", "saia": "saya", "salting": "salah tingkah", "sampe": "sampai", "samsek": "sama sekali", "sapose": "siapa", "satpam": "satuan pengamanan", "sbb": "sebagai berikut", "sbh": "sebuah", "sbnrny": "sebenarnya", "scr": "secara", "sdgkn": "sedangkan", "sdkt": "sedikit", "se7": "setuju", "sebelas dua belas": "mirip", "sembako": "sembilan bahan pokok", "sempet": "sempat", "sendratari": "seni drama tari", "sgt": "sangat", "shg": "sehingga", "siech": "sih", "sikon": "situasi dan kondisi", "sinetron": "sinema elektronik", "siramin": "siramkan", "sj": "saja", "skalian": "sekalian", "sklh": "sekolah", "skt": "sakit", "slesai": "selesai", "sll": "selalu", "slma": "selama", "slsai": "selesai", "smpt": "sempat", "smw": "semua", "sndiri": "sendiri", "soljum": "sholat jumat", "songong": "sombong", "sory": "maaf", "sosek": "sosial-ekonomi", "sotoy": "sok tahu", "spa": "siapa", "sppa": "siapa", "spt": "seperti", "srtfkt": "sertifikat", "stiap": "setiap", "stlh": "setelah", "suk": "masuk", "sumpek": "sempit", "syg": "sayang", "t4": "tempat", "tajir": "kaya", "tau": "tahu", "taw": "tahu", "td": "tadi", "tdk": "tidak", "teh": "kakak perempuan", "telat": "terlambat", "telmi": "telat berpikir", "temen": "teman", "tengil": "menyebalkan", "tepar": "terkapar", "tggu": "tunggu", "tgu": "tunggu", "thankz": "terima kasih", "thn": "tahun", "tilang": "bukti pelanggaran", "tipiwan": "TvOne", "tks": "terima kasih", "tlp": "telepon", "tls": "tulis", "tmbah": "tambah", "tmen2": "teman-teman", "tmpah": "tumpah", "tmpt": "tempat", "tngu": "tunggu", "tnyta": "ternyata", "tokai": "tai", "toserba": "toko serba ada", "tpi": "tapi", "trdhulu": "terdahulu", "trima": "terima kasih", "trm": "terima", "trs": "terus", "trutama": "terutama", "ts": "penulis", "tst": "tahu sama tahu", "ttg": "tentang", "tuch": "tuh", "tuir": "tua", "tw": "tahu", "u": "kamu", "ud": "sudah", "udah": "sudah", "ujg": "ujung", "ul": "ulangan", "unyu": "lucu", "uplot": "unggah", "urang": "saya", "usah": "perlu", "utk": "untuk", "valas": "valuta asing", "w/": "dengan", "wadir": "wakil direktur", "wamil": "wajib militer", "warkop": "warung kopi", "warteg": "warung tegal", "wat": "buat", "wkt": "waktu", "wtf": "what the fuck", "xixixi": "tertawa", "ya": "iya", "yap": "iya", "yaudah": "ya sudah", "yawdah": "ya sudah", "yg": "yang", "yl": "yang lain", "yo": "iya", "yowes": "ya sudah", "yup": "iya", "7an": "tujuan", "ababil": "abg labil", "acc": "accord", "adlah": "adalah", "adoh": "aduh", "aha": "tertawa", "aing": "saya", "aja": "saja", "ajj": "saja", "aka": "dikenal juga sebagai", "akko": "aku", "akku": "aku", "akyu": "aku", "aljasa": "asal jadi saja", "ama": "sama", "ambl": "ambil", "anjir": "anjing", "ank": "anak", "ap": "apa", "apaan": "apa", "ape": "apa", "aplot": "unggah", "apva": "apa", "aqu": "aku", "asap": "sesegera mungkin", "aseek": "asyik", "asek": "asyik", "aseknya": "asyiknya", "asoy": "asyik", "astrojim": "astagfirullahaladzim", "ath": "kalau begitu", "atuh": "kalau begitu", "ava": "avatar", "aws": "awas", "ayang": "sayang", "ayok": "ayo", "bacot": "banyak bicara", "bales": "balas", "bangdes": "pembangunan desa", "bangkotan": "tua", "banpres": "bantuan presiden", "bansarkas": "bantuan sarana kesehatan", "bazis": "badan amal, zakat, infak, dan sedekah", "bcoz": "karena", "beb": "sayang", "bejibun": "banyak", "belom": "belum", "bener": "benar", "ber2": "berdua", "berdikari": "berdiri di atas kaki sendiri", "bet": "banget", "beti": "beda tipis", "beut": "banget", "bgd": "banget", "bgs": "bagus", "bhubu": "tidur", "bimbuluh": "bimbingan dan penyuluhan", "bisi": "kalau-kalau", "bkn": "bukan", "bl": "beli", "blg": "bilang", "blm": "belum", "bls": "balas", "bnchi": "benci", "bngung": "bingung", "bnyk": "banyak", "bohay": "badan aduhai", "bokep": "porno", "bokin": "pacar", "bole": "boleh", "bolot": "bodoh", "bonyok": "ayah ibu", "bpk": "bapak", "brb": "segera kembali", "brngkt": "berangkat", "brp": "berapa", "brur": "saudara laki-laki", "bsa": "bisa", "bsk": "besok", "bu_bu": "tidur", "bubarin": "bubarkan", "buber": "buka bersama", "bujubune": "luar biasa", "buser": "buru sergap", "bwhn": "bawahan", "byar": "bayar", "byr": "bayar", "c8": "chat", "cabut": "pergi", "caem": "cakep", "cama-cama": "sama-sama", "cangcut": "celana dalam", "cape": "capek", "caur": "jelek", "cekak": "tidak ada uang", "cekidot": "coba lihat", "cemplungin": "cemplungkan", "ceper": "pendek", "ceu": "kakak perempuan", "cewe": "cewek", "cibuk": "sibuk", "cin": "cinta", "ciye": "cie", "ckck": "ck", "clbk": "cinta lama bersemi kembali", "cmpr": "campur", "cnenk": "senang", "congor": "mulut", "cow": "cowok", "coz": "karena", "cpa": "siapa", "gokil": "gila", "gombal": "suka merayu", "gpl": "tidak pakai lama", "gpp": "tidak apa-apa", "gretong": "gratis", "gt": "begitu", "gtw": "tidak tahu", "gue": "saya", "guys": "teman-teman", "gws": "cepat sembuh", "haghaghag": "tertawa", "hakhak": "tertawa", "handak": "bahan peledak", "hansip": "pertahanan sipil", "hellow": "halo", "helow": "halo", "hi": "hai", "hlng": "hilang", "hnya": "hanya", "houm": "rumah", "hrs": "harus", "hubad": "hubungan angkatan darat", "hubla": "perhubungan laut", "huft": "mengeluh", "humas": "hubungan masyarakat", "idk": "saya tidak tahu", "ilfeel": "tidak suka", "imba": "jago sekali", "imoet": "imut", "info": "informasi", "itung": "hitung", "isengin": "bercanda", "iyala": "iya lah", "iyo": "iya", "jablay": "jarang dibelai", "jadul": "jaman dulu", "jancuk": "anjing", "jd": "jadi", "jdikan": "jadikan", "jg": "juga", "jgn": "jangan", "jijay": "jijik", "jkt": "jakarta", "jnj": "janji", "jth": "jatuh", "jurdil": "jujur adil", "jwb": "jawab", "ka": "kakak", "kabag": "kepala bagian", "kacian": "kasihan", "kadit": "kepala direktorat", "kaga": "tidak", "kaka": "kakak", "kamtib": "keamanan dan ketertiban", "kamuh": "kamu", "kamyu": "kamu", "kapt": "kapten", "kasat": "kepala satuan", "kasubbid": "kepala subbidang", "kau": "kamu", "kbar": "kabar", "kcian": "kasihan", "keburu": "terlanjur", "kedubes": "kedutaan besar", "kek": "seperti", "keknya": "kayaknya", "keliatan": "kelihatan", "keneh": "masih", "kepikiran": "terpikirkan", "kepo": "mau tahu urusan orang", "kere": "tidak punya uang", "kesian": "kasihan", "ketauan": "ketahuan", "keukeuh": "keras kepala", "khan": "kan", "kibus": "kaki busuk", "kk": "kakak", "klian": "kalian", "klo": "kalau", "kluarga": "keluarga", "klwrga": "keluarga", "kmari": "kemari", "kmpus": "kampus", "kn": "kan", "knl": "kenal", "knpa": "kenapa", "kog": "kok", "kompi": "komputer", "komtiong": "komunis Tiongkok", "konjen": "konsulat jenderal", "koq": "kok", "kpd": "kepada", "kptsan": "keputusan", "krik": "garing", "krn": "karena", "ktauan": "ketahuan", "ktny": "katanya", "kudu": "harus", "kuq": "kok", "ky": "seperti", "kykny": "kayanya", "laka": "kecelakaan", "lambreta": "lambat", "lansia": "lanjut usia", "lapas": "lembaga pemasyarakatan", "lbur": "libur", "lekong": "laki-laki", "lg": "lagi", "lgkp": "lengkap", "lht": "lihat", "linmas": "perlindungan masyarakat", "lmyan": "lumayan", "lngkp": "lengkap", "loch": "loh", "lol": "tertawa", "lom": "belum", "loupz": "cinta", "lowh": "kamu", "lu": "kamu", "luchu": "lucu", "luff": "cinta", "luph": "cinta", "lw": "kamu", "lwt": "lewat", "maaciw": "terima kasih", "mabes": "markas besar", "macem-macem": "macam-macam", "madesu": "masa depan suram", "maen": "main", "mahatma": "maju sehat bersama", "mak": "ibu", "makasih": "terima kasih", "malah": "bahkan", "malu2in": "memalukan", "mamz": "makan", "manies": "manis", "mantep": "mantap", "markus": "makelar kasus", "mba": "mbak", "mending": "lebih baik", "mgkn": "mungkin", "mhn": "mohon", "miker": "minuman keras", "milis": "mailing list", "mksd": "maksud", "mls": "malas", "mnt": "minta", "moge": "motor gede", "mokat": "mati", "mosok": "masa", "msh": "masih", "mskpn": "meskipun", "msng2": "masing-masing", "muahal": "mahal", "muker": "musyawarah kerja", "mumet": "pusing", "muna": "munafik", "munaslub": "musyawarah nasional luar biasa", "musda": "musyawarah daerah", "muup": "maaf", "muuv": "maaf", "nal": "kenal", "nangis": "menangis", "naon": "apa", "napol": "narapidana politik", "naq": "anak", "narsis": "bangga pada diri sendiri", "nax": "anak", "ndak": "tidak", "ndut": "gendut", "nekolim": "neokolonialisme", "nelfon": "menelepon", "ngabis2in": "menghabiskan", "ngakak": "tertawa", "ngambek": "marah", "ngampus": "pergi ke kampus", "ngantri": "mengantri", "ngapain": "sedang apa", "ngaruh": "berpengaruh", "ngawur": "berbicara sembarangan", "ngeceng": "kumpul bareng-bareng", "ngeh": "sadar", "ngekos": "tinggal di kos", "ngelamar": "melamar", "ngeliat": "melihat", "ngemeng": "bicara terus-terusan", "ngerti": "mengerti", "nggak": "tidak", "ngikut": "ikut", "nginep": "menginap", "ngisi": "mengisi", "ngmg": "bicara", "ngocol": "lucu", "ngomongin": "membicarakan", "ngumpul": "berkumpul", "ni": "ini", "nyasar": "tersesat", "nyariin": "mencari", "nyiapin": "mempersiapkan", "nyiram": "menyiram", "nyok": "ayo", "o/": "oleh", "ok": "ok", "priksa": "periksa", "pro": "profesional", "psn": "pesan", "psti": "pasti", "puanas": "panas", "qmo": "kamu", "qt": "kita", "rame": "ramai", "raskin": "rakyat miskin", "red": "redaksi", "reg": "register", "rejeki": "rezeki", "renstra": "rencana strategis", "reskrim": "reserse kriminal", "sni": "sini", "somse": "sombong sekali", "sorry": "maaf", "sosbud": "sosial-budaya", "sospol": "sosial-politik", "sowry": "maaf", "spd": "sepeda", "sprti": "seperti", "spy": "supaya", "stelah": "setelah", "subbag": "subbagian", "sumbangin": "sumbangkan", "sy": "saya", "syp": "siapa", "tabanas": "tabungan pembangunan nasional", "tar": "nanti", "taun": "tahun", "tawh": "tahu", "tdi": "tadi", "te2p": "tetap", "tekor": "rugi", "telkom": "telekomunikasi", "telp": "telepon", "temen2": "teman-teman", "tengok": "menjenguk", "terbitin": "terbitkan", "tgl": "tanggal", "thanks": "terima kasih", "thd": "terhadap", "thx": "terima kasih", "tipi": "TV", "tkg": "tukang", "tll": "terlalu", "tlpn": "telepon", "tman": "teman", "tmbh": "tambah", "tmn2": "teman-teman", "tmph": "tumpah", "tnda": "tanda", "tnh": "tanah", "togel": "toto gelap", "tp": "tapi", "tq": "terima kasih", "trgntg": "tergantung", "trims": "terima kasih", "cb": "coba", "y": "ya", "munfik": "munafik", "reklamuk": "reklamasi", "sma": "sama", "tren": "trend", "ngehe": "kesal", "mz": "mas", "analisise": "analisis", "sadaar": "sadar", "sept": "september", "nmenarik": "menarik", "zonk": "bodoh", "rights": "benar", "simiskin": "miskin", "ngumpet": "sembunyi", "hardcore": "keras", "akhirx": "akhirnya", "solve": "solusi", "watuk": "batuk", "ngebully": "intimidasi", "masy": "masyarakat", "still": "masih", "tauk": "tahu", "mbual": "bual", "tioghoa": "tionghoa", "ngentotin": "senggama", "kentot": "senggama", "faktakta": "fakta", "sohib": "teman", "rubahnn": "rubah", "trlalu": "terlalu", "nyela": "cela", "heters": "pembenci", "nyembah": "sembah", "most": "paling", "ikon": "lambang", "light": "terang", "pndukung": "pendukung", "setting": "atur", "seting": "akting", "next": "lanjut", "waspadalah": "waspada", "gantengsaya": "ganteng", "parte": "partai", "nyerang": "serang", "nipu": "tipu", "ktipu": "tipu", "jentelmen": "berani", "buangbuang": "buang", "tsangka": "tersangka", "kurng": "kurang", "ista": "nista", "less": "kurang", "koar": "teriak", "paranoid": "takut", "problem": "masalah", "tahi": "kotoran", "tirani": "tiran", "tilep": "tilap", "happy": "bahagia", "tak": "tidak", "penertiban": "tertib", "uasai": "kuasa", "mnolak": "tolak", "trending": "trend", "taik": "tahi", "wkwkkw": "tertawa", "ahokncc": "ahok", "istaa": "nista", "benarjujur": "jujur", "mgkin": "mungkin"}
def fix_slangwords(text):
    words = text.split()
    fixed_words = []

    for word in words:
        if word.lower() in slangwords:
            fixed_words.append(slangwords[word.lower()])
        else:
            fixed_words.append(word)

    fixed_text = ' '.join(fixed_words)
    return fixed_text

In [7]:
# Membersihkan teks dan menyimpannya di kolom 'text_clean'
df['text_clean'] = df['content'].apply(cleaningText)

# Mengubah huruf dalam teks menjadi huruf kecil dan menyimpannya di 'text_casefoldingText'
df['text_casefoldingText'] = df['text_clean'].apply(casefoldingText)

# Mengganti kata-kata slang dengan kata-kata standar dan menyimpannya di 'text_slangwords'
df['text_slangwords'] = df['text_casefoldingText'].apply(fix_slangwords)

# Memecah teks menjadi token (kata-kata) dan menyimpannya di 'text_tokenizingText'
df['text_tokenizingText'] = df['text_slangwords'].apply(tokenizingText)

# Menghapus kata-kata stop (kata-kata umum) dan menyimpannya di 'text_stopword'
df['text_stopword'] = df['text_tokenizingText'].apply(filteringText)

# Menggabungkan token-token menjadi kalimat dan menyimpannya di 'text_akhir'
df['text_akhir'] = df['text_stopword'].apply(toSentence)

In [8]:
# Mengatur opsi tampilan Pandas agar kolom dapat menampilkan teks hingga 3000 karakter.
pd.set_option('display.max_colwidth', 3000)
df

,content,text_clean,text_casefoldingText,text_slangwords,text_tokenizingText,text_stopword,text_akhir
0,semuanya yg ada di ruang guru sangat bagus tetapi ketika Saya mau mengerjakan drill soal selalu saja soalnya tidak bisa di geser sudah di coba berulang kali tetap gak bisa . Tolong dong di perbaiki sistem nya masa cuma chat wa aja yg cepat tetapi sistem nya tidak dapat cepat bekerja.,semuanya yg ada di ruang guru sangat bagus tetapi ketika Saya mau mengerjakan drill soal selalu saja soalnya tidak bisa di geser sudah di coba berulang kali tetap gak bisa Tolong dong di perbaiki sistem nya masa cuma chat wa aja yg cepat tetapi sistem nya tidak dapat cepat bekerja,semuanya yg ada di ruang guru sangat bagus tetapi ketika saya mau mengerjakan drill soal selalu saja soalnya tidak bisa di geser sudah di coba berulang kali tetap gak bisa tolong dong di perbaiki sistem nya masa cuma chat wa aja yg cepat tetapi sistem nya tidak dapat cepat bekerja,semuanya yang ada di ruang guru sangat bagus tetapi ketika saya mau mengerjakan drill soal selalu saja soalnya tidak bisa di geser sudah di coba berulang kali tetap gak bisa tolong dong di perbaiki sistem nya masa cuma chat wa saja yang cepat tetapi sistem nya tidak dapat cepat bekerja,"[semuanya, yang, ada, di, ruang, guru, sangat, bagus, tetapi, ketika, saya, mau, mengerjakan, drill, soal, selalu, saja, soalnya, tidak, bisa, di, geser, sudah, di, coba, berulang, kali, tetap, gak, bisa, tolong, dong, di, perbaiki, sistem, nya, masa, cuma, chat, wa, saja, yang, cepat, tetapi, sistem, nya, tidak, dapat, cepat, bekerja]","[ruang, guru, bagus, drill, geser, coba, berulang, kali, tolong, perbaiki, sistem, chat, wa, cepat, sistem, cepat]",ruang guru bagus drill geser coba berulang kali tolong perbaiki sistem chat wa cepat sistem cepat
1,"saya lagi nonton video pembelajaran nih, dimana video pembelajarannnya akan berakhir ±1 menit kemudian. Sedangkan saya posisinya masih mengerjakan soal dari latihan soal yang ada dalam video. Belum rampung saya menjawab, itu tiba tiba keluar notifikasi untuk lanjut ke fitur kuis. Untuk lanjut ke fitur kuisnya kan dihitung mundur, tapi bisa dibatalkan. Namun, saat dibatalkan, opsi fiturnyakan masih ada di videonya. Nah itu menggangu untuk saya menjawab soal, karena opsinya menutupi jawaban",saya lagi nonton video pembelajaran nih dimana video pembelajarannnya akan berakhir menit kemudian Sedangkan saya posisinya masih mengerjakan soal dari latihan soal yang ada dalam video Belum rampung saya menjawab itu tiba tiba keluar notifikasi untuk lanjut ke fitur kuis Untuk lanjut ke fitur kuisnya kan dihitung mundur tapi bisa dibatalkan Namun saat dibatalkan opsi fiturnyakan masih ada di videonya Nah itu menggangu untuk saya menjawab soal karena opsinya menutupi jawaban,saya lagi nonton video pembelajaran nih dimana video pembelajarannnya akan berakhir menit kemudian sedangkan saya posisinya masih mengerjakan soal dari latihan soal yang ada dalam video belum rampung saya menjawab itu tiba tiba keluar notifikasi untuk lanjut ke fitur kuis untuk lanjut ke fitur kuisnya kan dihitung mundur tapi bisa dibatalkan namun saat dibatalkan opsi fiturnyakan masih ada di videonya nah itu menggangu untuk saya menjawab soal karena opsinya menutupi jawaban,saya lagi nonton video pembelajaran ini dimana video pembelajarannnya akan berakhir menit kemudian sedangkan saya posisinya masih mengerjakan soal dari latihan soal yang ada dalam video belum rampung saya menjawab itu tiba tiba keluar notifikasi untuk lanjut ke fitur kuis untuk lanjut ke fitur kuisnya kan dihitung mundur tapi bisa dibatalkan namun saat dibatalkan opsi fiturnyakan masih ada di videonya nah itu menggangu untuk saya menjawab soal karena opsinya menutupi jawaban,"[saya, lagi, nonton, video, pembelajaran, ini, dimana, video, pembelajarannnya, akan, berakhir, menit, kemudian, sedangkan, saya, posisinya, masih, mengerjakan, soal, dari, latihan, soal, yang, ada, dalam, video, belum, rampung, saya, menjawab, itu, tiba, tiba, keluar, notifikasi, untuk, lanjut, ke, fitur, kuis, untuk, lanjut, ke, fitur, kuisnya, kan, dihitung, mundur, tapi, bisa, dibatalkan, namun, saat, dibatalkan, opsi, fiturnyakan, masih, ada, di, videonya, nah, itu, menggangu, untuk, saya, menjawab, soal, karena, opsinya, menutupi, jawaban]","[nonton, video, pembelajaran, dimana, video, pembelajarannnya, menit, posisinya, latihan, video, rampung, notifikasi, fitur, kuis, fitur, kuisnya, dihitung, mundur, dibatalkan, dibatalkan, opsi, fiturnyakan, videonya, menggangu, opsinya, menutupi]",nonton video pembelajaran dimana video pembelajarannnya menit posisinya latihan video rampung notifikasi fitur kuis fitur kuisnya dihitung mundur dibatalkan dibatalkan opsi fiturnyakan videonya menggangu opsinya menutupi
2,"bagus banget nih buat belajar, untuk sekarang aku masih kadang²liat vid pembelajaran di RUANG GURU, bisa di sesuaikan juga untuk kelas berapa nya, jadi kalo liat vid pembelajaran, sesuai sama materi yang ada di sekolah 🏫, ini juga untuk persiapan buat kelas 8 supaya aku bisa lebih ningkatin skill belajar aku untuk dapetin nilai yang bagus, sekaligus biar bisa lebih paham untuk memahami materi di sekolah, aku download apk ini karena aku mau ngalahin temen aku supaya aku bisa rebut rank ke 2 🤭",bagus banget nih buat belajar untuk sekarang aku masih kadang²liat vid pembelajaran di RUANG GURU bisa di sesuaikan juga untuk kelas berapa nya jadi kalo liat vid pembelajaran sesuai sama materi yang ada di sekolah ini juga untuk persiapan buat kelas supaya aku bisa lebih ningkatin skill belajar aku untuk dapetin nilai yang bagus sekaligus biar bisa lebih paham untuk memahami materi di sekolah aku download apk ini karena aku mau ngalahin temen aku supaya aku bisa rebut rank ke,bagus banget nih buat belajar untuk sekarang aku masih kadang²liat vid pembelajaran di ruang guru bisa di sesuaikan juga untuk kelas berapa nya jadi kalo liat vid pembelajaran sesuai sama materi yang ada di sekolah ini juga untuk persiapan buat kelas supaya aku bisa lebih ningkatin skill belajar aku untuk dapetin nilai yang bagus sekaligus biar bisa lebih paham untuk memahami materi di sekolah aku download apk ini karena aku mau ngalahin temen aku supaya aku bisa rebut rank ke,bagus banget ini buat belajar untuk sekarang aku masih kadang²liat vid pembelajaran di ruang guru bisa di sesuaikan juga untuk kelas berapa nya jadi kalau lihat vid pembelajaran sesuai sama materi yang ada di sekolah ini juga untuk persiapan buat kelas supaya aku bisa lebih ningkatin skill belajar aku untuk dapetin nilai yang bagus sekaligus biar bisa lebih paham untuk memahami materi di sekolah aku download apk ini karena aku mau ngalahin teman aku supaya aku bisa rebut rank ke,"[bagus, banget, ini, buat, belajar, untuk, sekarang, aku, masih, kadang²liat, vid, pembelajaran, di, ruang, guru, bisa, di, sesuaikan, juga, untuk, kelas, berapa, nya, jadi, kalau, lihat, vid, pembelajaran, sesuai, sama, materi, yang, ada, di, sekolah, ini, juga, untuk, persiapan, buat, kelas, supaya, aku, bisa, lebih, ningkatin, skill, belajar, aku, untuk, dapetin, nilai, yang, bagus, sekaligus, biar, bisa, lebih, paham, untuk, memahami, materi, di, sekolah, aku, download, apk, ini, karena, aku, mau, ngalahin, teman, aku, supaya, aku, bisa, rebut, rank, ke]","[bagus, banget, belajar, kadang²liat, vid, pembelajaran, ruang, guru, sesuaikan, kelas, lihat, vid, pembelajaran, sesuai, materi, sekolah, persiapan, kelas, ningkatin, skill, belajar, dapetin, nilai, bagus, biar, paham, memahami, materi, sekolah, download, apk, ngalahin, teman, rebut, rank]",bagus banget belajar kadang²liat vid pembelajaran ruang guru sesuaikan kelas lihat vid pembelajaran sesuai materi sekolah persiapan kelas ningkatin skill belajar dapetin nilai bagus biar paham memahami materi sekolah download apk ngalahin teman rebut rank
3,"Overall semuanya tampak bagus, tapi tolong developer Tambahkan mode gelap dan tampilan aplikasi bisa jadi landscape, dan widget ruangguru itu bisa mirip aplikasi bahasa burung ijo sebelah. Semoga bisa improve setelahnya. Good job squad",Overall semuanya tampak bagus tapi tolong developer Tambahkan mode gelap dan tampilan aplikasi bisa jadi landscape dan widget ruangguru itu bisa mirip aplikasi bahasa burung ijo sebelah Semoga bisa improve setelahnya Good job squad,overall semuanya tampak bagus tapi tolong developer tambahkan mode gelap dan tampilan aplikasi bisa jadi landscape dan widget ruangguru itu bisa mirip aplikasi bahasa burung ijo sebelah semoga bisa improve setelahnya good job squad,overall semuanya tampak bagus tapi tolong developer tambahkan mode gelap dan tampilan aplikasi bisa jadi landscape dan widget ruangguru itu bisa mirip aplikasi bahasa burung ijo sebelah semoga bisa improve setelahnya good job squad,"[overall, semuanya, tampak, bagus, tapi, tolong, developer, tambahkan, mode, gelap, dan, tampilan, aplikasi, bisa, jadi, landscape, dan, widget, ruangguru, itu, bisa, mirip, aplikasi, bahasa, burung, ijo, sebelah, semoga, bisa, improve, setelahnya, good, job, squad]","[overall, bagus, tolong, developer, tambahkan, mode, gelap, tampilan, aplikasi, landscape, widget, ruangguru, aplikasi, bahasa, burung, ijo, sebelah, semoga, improve, setelahnya, good, job, squad]",overall bagus tolong developer tambahkan mode gelap tampilan aplikasi landscape widget ruangguru aplikasi bahasa burung ijo sebelah semoga improve setelahnya good job squad
4,"ruangguru benar² menjadi ruang yang menyenangkan untuk belajar, materinya lengkap, pengajar²nya kompeten dan ditambah ada filter adapto yang memudahkan untuk memahami pelajaran, terima kasih ruangguru telah hadir.....",ruangguru benar² menjadi ruang yang menyenangkan untuk belajar materinya lengkap pengajar²nya kompeten dan ditambah ada filter adapto yang memudahkan untuk memahami pelajaran terima kasih ruangguru telah hadir,ruangguru benar² menjadi ruang yang menyenangkan untuk belajar materinya lengkap pengajar²nya kompeten dan ditambah ada filter adapto yang memudahkan untuk memahami pelajaran terima kasih ruangguru telah hadir,ruangguru benar² menjadi ruang yang menyenangkan untuk belajar materinya lengkap pengajar²nya kompeten dan ditambah ada filter adapto yang memudahkan untuk memahami pelajaran terima kasih ruangguru telah hadir,"[ruangguru, benar², menjadi, ruang, yang, menyenangkan, untuk, belajar, materinya, lengkap, pengajar²nya, kompeten, dan, ditambah, ada, filter, adapto, yang, memudahkan, untuk, memahami, pelajaran, terima, kasih, ruangguru, telah, hadir]","[ruangguru, benar², ruang, menyenangkan, belajar, materinya, lengkap, pengajar²nya, kompeten, ditambah, filter, adapto, memudahkan, memahami, pelajaran, terima, kasih, ruangguru, hadir]",ruangguru benar² ruang menyenangkan belajar materinya lengkap pengajar²nya kompeten ditambah filter adapto memudahkan memahami pelajaran terima kasih ruangguru hadir
...,...,...,...,...,...,...,...
21586,mendapatkan sebuah pelajaran yang lebih efektif atau lebih mudah untuk dipahami,mendapatkan sebuah pelajaran yang lebih efektif atau lebih mudah untuk dipahami,mendapatkan sebuah pelajaran yang lebih efektif atau lebih mudah untuk dipahami,mendapatkan sebuah pelajaran yang lebih efektif atau lebih mudah untuk dipahami,"[mendapatkan, sebuah, pelajaran, yang, lebih, efektif, atau, lebih, mudah, untuk, dipahami]","[pelajaran, efektif, mudah, dipahami]",pelajaran efektif mudah dipahami
21587,Aplikasi ini membuat saya semakin ngerti tentang matematika dan mata pelajaran yg Lainnya,Aplikasi ini membuat saya semakin ngerti tentang matematika dan mata pelajaran yg Lainnya,aplikasi ini membuat saya semakin ngerti tentang matematika dan mata pelajaran yg lainnya,aplikasi ini membuat saya semakin mengerti tentang matematika dan mata pelajaran yang lainnya,"[aplikasi, ini, membuat, saya, semakin, mengerti, tentang, matematika, dan, mata, pelajaran, yang, lainnya]","[aplikasi, mengerti, matematika, mata, pelajaran]",aplikasi mengerti matematika mata pelajaran
21588,yey bisa belajar lagi asah otak lagi guys tapi kok susah juga ya soal2 nya 😆,yey bisa belajar lagi asah otak lagi guys tapi kok susah juga ya soal nya,yey bisa belajar lagi asah otak lagi guys tapi kok susah juga ya soal nya,yey bisa belajar lagi asah otak lagi teman-teman tapi kok susah juga iya soal nya,"[yey, bisa, belajar, lagi, asah, otak, lagi, teman-teman, tapi, kok, susah, juga, iya, soal, nya]","[yey, belajar, asah, otak, teman-teman, susah]",yey belajar asah otak teman-teman susah
21589,aplikasi ini bagus sangat ber prestasi da selamat ulang tahun Ruangguru yang ke 5😁,aplikasi ini bagus sangat ber prestasi da selamat ulang tahun Ruangguru yang ke,aplikasi ini bagus sangat ber prestasi da selamat ulang tahun ruangguru yang ke,aplikasi ini bagus sangat ber prestasi da selamat ulang tahun ruangguru yang ke,"[aplikasi, ini, bagus, sangat, ber, prestasi, da, selamat, ulang, tahun, ruangguru, yang, ke]","[aplikasi, bagus, ber, prestasi, da, selamat, ulang, ruangguru]",aplikasi bagus ber prestasi da selamat ulang ruangguru
21590,"Ruangguru sangat bermanfaat sekali untuk saya belajar, terimakasih ruangguru.",Ruangguru sangat bermanfaat sekali untuk saya belajar terimakasih ruangguru,ruangguru sangat bermanfaat sekali untuk saya belajar terimakasih ruangguru,ruangguru sangat bermanfaat sekali untuk saya belajar terimakasih ruangguru,"[ruangguru, sangat, bermanfaat, sekali, untuk, saya, belajar, terimakasih, ruangguru]","[ruangguru, bermanfaat, belajar, terimakasih, ruangguru]",ruangguru bermanfaat belajar terimakasih ruangguru

# Labelling menggunakan Lexicon

In [9]:
import csv
import requests
from io import StringIO

# Loads positive lexicon data from GitHub
# Membaca data kamus kata-kata positif dari GitHub
lexicon_positive = dict()

response = requests.get('https://raw.githubusercontent.com/angelmetanosaa/dataset/main/lexicon_positive.csv')
# Mengirim permintaan HTTP untuk mendapatkan file CSV dari GitHub

if response.status_code == 200:
    # Jika permintaan berhasil
    reader = csv.reader(StringIO(response.text), delimiter=',')
    # Membaca teks respons sebagai file CSV menggunakan pembaca CSV dengan pemisah koma

    for row in reader:
        # Mengulangi setiap baris dalam file CSV
        lexicon_positive[row[0]] = int(row[1])
        # Menambahkan kata-kata positif dan skornya ke dalam kamus lexicon_positive
else:
    print("Failed to fetch positive lexicon data")

# Loads negative lexicon data from GitHub
# Membaca data kamus kata-kata negatif dari GitHub
lexicon_negative = dict()

response = requests.get('https://raw.githubusercontent.com/angelmetanosaa/dataset/main/lexicon_negative.csv')
# Mengirim permintaan HTTP untuk mendapatkan file CSV dari GitHub

if response.status_code == 200:
    # Jika permintaan berhasil
    reader = csv.reader(StringIO(response.text), delimiter=',')
    # Membaca teks respons sebagai file CSV menggunakan pembaca CSV dengan pemisah koma

    for row in reader:
        # Mengulangi setiap baris dalam file CSV
        lexicon_negative[row[0]] = int(row[1])
        # Menambahkan kata-kata negatif dan skornya ke dalam kamus lexicon_negative
else:
    print("Failed to fetch negative lexicon data")

In [10]:
# Function to determine sentiment polarity of tweets
# Fungsi untuk menentukan polaritas sentimen dari tweet

def sentiment_analysis_lexicon_indonesia(text):
    #for word in text:

    score = 0
    # Inisialisasi skor sentimen ke 0

    for word in text:
        # Mengulangi setiap kata dalam teks

        if (word in lexicon_positive):
            score = score + lexicon_positive[word]
            # Jika kata ada dalam kamus positif, tambahkan skornya ke skor sentimen

    for word in text:
        # Mengulangi setiap kata dalam teks (sekali lagi)

        if (word in lexicon_negative):
            score = score + lexicon_negative[word]
            # Jika kata ada dalam kamus negatif, kurangkan skornya dari skor sentimen

    polarity=''
    # Inisialisasi variabel polaritas

    if (score >= 0):
        polarity = 'positive'
        # Jika skor sentimen lebih besar atau sama dengan 0, maka polaritas adalah positif
    elif (score < 0):
        polarity = 'negative'
        # Jika skor sentimen kurang dari 0, maka polaritas adalah negatif

    # else:
    #     polarity = 'neutral'
    # Ini adalah bagian yang bisa digunakan untuk menentukan polaritas netral jika diperlukan

    return score, polarity
    # Mengembalikan skor sentimen dan polaritas teks

In [11]:
results = df['text_stopword'].apply(sentiment_analysis_lexicon_indonesia)
results = list(zip(*results))
df['polarity_score'] = results[0]
df['polarity'] = results[1]
print(df['polarity'].value_counts())

polarity
positive    15757
negative     5834
Name: count, dtype: int64

In [12]:
df

,content,text_clean,text_casefoldingText,text_slangwords,text_tokenizingText,text_stopword,text_akhir,polarity_score,polarity
0,semuanya yg ada di ruang guru sangat bagus tetapi ketika Saya mau mengerjakan drill soal selalu saja soalnya tidak bisa di geser sudah di coba berulang kali tetap gak bisa . Tolong dong di perbaiki sistem nya masa cuma chat wa aja yg cepat tetapi sistem nya tidak dapat cepat bekerja.,semuanya yg ada di ruang guru sangat bagus tetapi ketika Saya mau mengerjakan drill soal selalu saja soalnya tidak bisa di geser sudah di coba berulang kali tetap gak bisa Tolong dong di perbaiki sistem nya masa cuma chat wa aja yg cepat tetapi sistem nya tidak dapat cepat bekerja,semuanya yg ada di ruang guru sangat bagus tetapi ketika saya mau mengerjakan drill soal selalu saja soalnya tidak bisa di geser sudah di coba berulang kali tetap gak bisa tolong dong di perbaiki sistem nya masa cuma chat wa aja yg cepat tetapi sistem nya tidak dapat cepat bekerja,semuanya yang ada di ruang guru sangat bagus tetapi ketika saya mau mengerjakan drill soal selalu saja soalnya tidak bisa di geser sudah di coba berulang kali tetap gak bisa tolong dong di perbaiki sistem nya masa cuma chat wa saja yang cepat tetapi sistem nya tidak dapat cepat bekerja,"[semuanya, yang, ada, di, ruang, guru, sangat, bagus, tetapi, ketika, saya, mau, mengerjakan, drill, soal, selalu, saja, soalnya, tidak, bisa, di, geser, sudah, di, coba, berulang, kali, tetap, gak, bisa, tolong, dong, di, perbaiki, sistem, nya, masa, cuma, chat, wa, saja, yang, cepat, tetapi, sistem, nya, tidak, dapat, cepat, bekerja]","[ruang, guru, bagus, drill, geser, coba, berulang, kali, tolong, perbaiki, sistem, chat, wa, cepat, sistem, cepat]",ruang guru bagus drill geser coba berulang kali tolong perbaiki sistem chat wa cepat sistem cepat,-9,negative
1,"saya lagi nonton video pembelajaran nih, dimana video pembelajarannnya akan berakhir ±1 menit kemudian. Sedangkan saya posisinya masih mengerjakan soal dari latihan soal yang ada dalam video. Belum rampung saya menjawab, itu tiba tiba keluar notifikasi untuk lanjut ke fitur kuis. Untuk lanjut ke fitur kuisnya kan dihitung mundur, tapi bisa dibatalkan. Namun, saat dibatalkan, opsi fiturnyakan masih ada di videonya. Nah itu menggangu untuk saya menjawab soal, karena opsinya menutupi jawaban",saya lagi nonton video pembelajaran nih dimana video pembelajarannnya akan berakhir menit kemudian Sedangkan saya posisinya masih mengerjakan soal dari latihan soal yang ada dalam video Belum rampung saya menjawab itu tiba tiba keluar notifikasi untuk lanjut ke fitur kuis Untuk lanjut ke fitur kuisnya kan dihitung mundur tapi bisa dibatalkan Namun saat dibatalkan opsi fiturnyakan masih ada di videonya Nah itu menggangu untuk saya menjawab soal karena opsinya menutupi jawaban,saya lagi nonton video pembelajaran nih dimana video pembelajarannnya akan berakhir menit kemudian sedangkan saya posisinya masih mengerjakan soal dari latihan soal yang ada dalam video belum rampung saya menjawab itu tiba tiba keluar notifikasi untuk lanjut ke fitur kuis untuk lanjut ke fitur kuisnya kan dihitung mundur tapi bisa dibatalkan namun saat dibatalkan opsi fiturnyakan masih ada di videonya nah itu menggangu untuk saya menjawab soal karena opsinya menutupi jawaban,saya lagi nonton video pembelajaran ini dimana video pembelajarannnya akan berakhir menit kemudian sedangkan saya posisinya masih mengerjakan soal dari latihan soal yang ada dalam video belum rampung saya menjawab itu tiba tiba keluar notifikasi untuk lanjut ke fitur kuis untuk lanjut ke fitur kuisnya kan dihitung mundur tapi bisa dibatalkan namun saat dibatalkan opsi fiturnyakan masih ada di videonya nah itu menggangu untuk saya menjawab soal karena opsinya menutupi jawaban,"[saya, lagi, nonton, video, pembelajaran, ini, dimana, video, pembelajarannnya, akan, berakhir, menit, kemudian, sedangkan, saya, posisinya, masih, mengerjakan, soal, dari, latihan, soal, yang, ada, dalam, video, belum, rampung, saya, menjawab, itu, tiba, tiba, keluar, notifikasi, untuk, lanjut, ke, fitur, kuis, untuk, lanjut, ke, fitur, kuisnya, kan, dihitung, mundur, tapi, bisa, dibatalkan, namun, saat, dibatalkan, opsi, fiturnyakan, masih, ada, di, videonya, nah, itu, menggangu, untuk, saya, menjawab, soal, karena, opsinya, menutupi, jawaban]","[nonton, video, pembelajaran, dimana, video, pembelajarannnya, menit, posisinya, latihan, video, rampung, notifikasi, fitur, kuis, fitur, kuisnya, dihitung, mundur, dibatalkan, dibatalkan, opsi, fiturnyakan, videonya, menggangu, opsinya, menutupi]",nonton video pembelajaran dimana video pembelajarannnya menit posisinya latihan video rampung notifikasi fitur kuis fitur kuisnya dihitung mundur dibatalkan dibatalkan opsi fiturnyakan videonya menggangu opsinya menutupi,1,positive
2,"bagus banget nih buat belajar, untuk sekarang aku masih kadang²liat vid pembelajaran di RUANG GURU, bisa di sesuaikan juga untuk kelas berapa nya, jadi kalo liat vid pembelajaran, sesuai sama materi yang ada di sekolah 🏫, ini juga untuk persiapan buat kelas 8 supaya aku bisa lebih ningkatin skill belajar aku untuk dapetin nilai yang bagus, sekaligus biar bisa lebih paham untuk memahami materi di sekolah, aku download apk ini karena aku mau ngalahin temen aku supaya aku bisa rebut rank ke 2 🤭",bagus banget nih buat belajar untuk sekarang aku masih kadang²liat vid pembelajaran di RUANG GURU bisa di sesuaikan juga untuk kelas berapa nya jadi kalo liat vid pembelajaran sesuai sama materi yang ada di sekolah ini juga untuk persiapan buat kelas supaya aku bisa lebih ningkatin skill belajar aku untuk dapetin nilai yang bagus sekaligus biar bisa lebih paham untuk memahami materi di sekolah aku download apk ini karena aku mau ngalahin temen aku supaya aku bisa rebut rank ke,bagus banget nih buat belajar untuk sekarang aku masih kadang²liat vid pembelajaran di ruang guru bisa di sesuaikan juga untuk kelas berapa nya jadi kalo liat vid pembelajaran sesuai sama materi yang ada di sekolah ini juga untuk persiapan buat kelas supaya aku bisa lebih ningkatin skill belajar aku untuk dapetin nilai yang bagus sekaligus biar bisa lebih paham untuk memahami materi di sekolah aku download apk ini karena aku mau ngalahin temen aku supaya aku bisa rebut rank ke,bagus banget ini buat belajar untuk sekarang aku masih kadang²liat vid pembelajaran di ruang guru bisa di sesuaikan juga untuk kelas berapa nya jadi kalau lihat vid pembelajaran sesuai sama materi yang ada di sekolah ini juga untuk persiapan buat kelas supaya aku bisa lebih ningkatin skill belajar aku untuk dapetin nilai yang bagus sekaligus biar bisa lebih paham untuk memahami materi di sekolah aku download apk ini karena aku mau ngalahin teman aku supaya aku bisa rebut rank ke,"[bagus, banget, ini, buat, belajar, untuk, sekarang, aku, masih, kadang²liat, vid, pembelajaran, di, ruang, guru, bisa, di, sesuaikan, juga, untuk, kelas, berapa, nya, jadi, kalau, lihat, vid, pembelajaran, sesuai, sama, materi, yang, ada, di, sekolah, ini, juga, untuk, persiapan, buat, kelas, supaya, aku, bisa, lebih, ningkatin, skill, belajar, aku, untuk, dapetin, nilai, yang, bagus, sekaligus, biar, bisa, lebih, paham, untuk, memahami, materi, di, sekolah, aku, download, apk, ini, karena, aku, mau, ngalahin, teman, aku, supaya, aku, bisa, rebut, rank, ke]","[bagus, banget, belajar, kadang²liat, vid, pembelajaran, ruang, guru, sesuaikan, kelas, lihat, vid, pembelajaran, sesuai, materi, sekolah, persiapan, kelas, ningkatin, skill, belajar, dapetin, nilai, bagus, biar, paham, memahami, materi, sekolah, download, apk, ngalahin, teman, rebut, rank]",bagus banget belajar kadang²liat vid pembelajaran ruang guru sesuaikan kelas lihat vid pembelajaran sesuai materi sekolah persiapan kelas ningkatin skill belajar dapetin nilai bagus biar paham memahami materi sekolah download apk ngalahin teman rebut rank,15,positive
3,"Overall semuanya tampak bagus, tapi tolong developer Tambahkan mode gelap dan tampilan aplikasi bisa jadi landscape, dan widget ruangguru itu bisa mirip aplikasi bahasa burung ijo sebelah. Semoga bisa improve setelahnya. Good job squad",Overall semuanya tampak bagus tapi tolong developer Tambahkan mode gelap dan tampilan aplikasi bisa jadi landscape dan widget ruangguru itu bisa mirip aplikasi bahasa burung ijo sebelah Semoga bisa improve setelahnya Good job squad,overall semuanya tampak bagus tapi tolong developer tambahkan mode gelap dan tampilan aplikasi bisa jadi landscape dan widget ruangguru itu bisa mirip aplikasi bahasa burung ijo sebelah semoga bisa improve setelahnya good job squad,overall semuanya tampak bagus tapi tolong developer tambahkan mode gelap dan tampilan aplikasi bisa jadi landscape dan widget ruangguru itu bisa mirip aplikasi bahasa burung ijo sebelah semoga bisa improve setelahnya good job squad,"[overall, semuanya, tampak, bagus, tapi, tolong, developer, tambahkan, mode, gelap, dan, tampilan, aplikasi, bisa, jadi, landscape, dan, widget, ruangguru, itu, bisa, mirip, aplikasi, bahasa, burung, ijo, sebelah, semoga, bisa, improve, setelahnya, good, job, squad]","[overall, bagus, tolong, developer, tambahkan, mode, gelap, tampilan, aplikasi, landscape, widget, ruangguru, aplikasi, bahasa, burung, ijo, sebelah, semoga, improve, setelahnya, good, job, squad]",overall bagus tolong developer tambahkan mode gelap tampilan aplikasi landscape widget ruangguru aplikasi bahasa burung ijo sebelah semoga improve setelahnya good job squad,-15,negative
4,"ruangguru benar² menjadi ruang yang menyenangkan untuk belajar, materinya lengkap, pengajar²nya kompeten dan ditambah ada filter adapto yang memudahkan untuk memahami pelajaran, terima kasih ruangguru telah hadir.....",ruangguru benar² menjadi ruang yang menyenangkan untuk belajar materinya lengkap pengajar²nya kompeten dan ditambah ada filter adapto yang memudahkan untuk memahami pelajaran terima kasih ruangguru telah hadir,ruangguru benar² menjadi ruang yang menyenangkan untuk belajar materinya lengkap pengajar²nya kompeten dan ditambah ada filter adapto yang memudahkan untuk memahami pelajaran terima kasih ruangguru telah hadir,ruangguru benar² menjadi ruang yang menyenangkan untuk belajar materinya lengkap pengajar²nya kompeten dan ditambah ada filter adapto yang memudahkan untuk memahami pelajaran terima kasih ruangguru telah hadir,"[ruangguru, benar², menjadi, ruang, yang, menyenangkan, untuk, belajar, materinya, lengkap, pengajar²nya, kompeten, dan, ditambah, ada, filter, adapto, yang, memudahkan, untuk, memahami, pelajaran, terima, kasih, ruangguru, telah, hadir]","[ruangguru, benar², ruang, menyenangkan, belajar, materinya, lengkap, pengajar²nya, kompeten, ditambah, filter, adapto, memudahkan, memahami, pelajaran, terima, kasih, ruangguru, hadir]",ruangguru benar² ruang menyenangkan belajar materinya lengkap pengajar²nya kompeten ditambah filter adapto memudahkan memahami pelajaran terima kasih ruangguru hadir,9,positive
...,...,...,...,...,...,...,...,...,...
21586,mendapatkan sebuah pelajaran yang lebih efektif atau lebih mudah untuk dipahami,mendapatkan sebuah pelajaran yang lebih efektif atau lebih mudah untuk dipahami,mendapatkan sebuah pelajaran yang lebih efektif atau lebih mudah untuk dipahami,mendapatkan sebuah pelajaran yang lebih efektif atau lebih mudah untuk dipahami,"[mendapatkan, sebuah, pelajaran, yang, lebih, efektif, atau, lebih, mudah, untuk, dipahami]","[pelajaran, efektif, mudah, dipahami]",pelajaran efektif mudah dipahami,10,positive
21587,Aplikasi ini membuat saya semakin ngerti tentang matematika dan mata pelajaran yg Lainnya,Aplikasi ini membuat saya semakin ngerti tentang matematika dan mata pelajaran yg Lainnya,aplikasi ini membuat saya semakin ngerti tentang matematika dan mata pelajaran yg lainnya,aplikasi ini membuat saya semakin mengerti tentang matematika dan mata pelajaran yang lainnya,"[aplikasi, ini, membuat, saya, semakin, mengerti, tentang, matematika, dan, mata, pelajaran, yang, lainnya]","[aplikasi, mengerti, matematika, mata, pelajaran]",aplikasi mengerti matematika mata pelajaran,-4,negative
21588,yey bisa belajar lagi asah otak lagi guys tapi kok susah juga ya soal2 nya 😆,yey bisa belajar lagi asah otak lagi guys tapi kok susah juga ya soal nya,yey bisa belajar lagi asah otak lagi guys tapi kok susah juga ya soal nya,yey bisa belajar lagi asah otak lagi teman-teman tapi kok susah juga iya soal nya,"[yey, bisa, belajar, lagi, asah, otak, lagi, teman-teman, tapi, kok, susah, juga, iya, soal, nya]","[yey, belajar, asah, otak, teman-teman, susah]",yey belajar asah otak teman-teman susah,-3,negative
21589,aplikasi ini bagus sangat ber prestasi da selamat ulang tahun Ruangguru yang ke 5😁,aplikasi ini bagus sangat ber prestasi da selamat ulang tahun Ruangguru yang ke,aplikasi ini bagus sangat ber prestasi da selamat ulang tahun ruangguru yang ke,aplikasi ini bagus sangat ber prestasi da selamat ulang tahun ruangguru yang ke,"[aplikasi, ini, bagus, sangat, ber, prestasi, da, selamat, ulang, tahun, ruangguru, yang, ke]","[aplikasi, bagus, ber, prestasi, da, selamat, ulang, ruangguru]",aplikasi bagus ber prestasi da selamat ulang ruangguru,-1,negative
21590,"Ruangguru sangat bermanfaat sekali untuk saya belajar, terimakasih ruangguru.",Ruangguru sangat bermanfaat sekali untuk saya belajar terimakasih ruangguru,ruangguru sangat bermanfaat sekali untuk saya belajar terimakasih ruangguru,ruangguru sangat bermanfaat sekali untuk saya belajar terimakasih ruangguru,"[ruangguru, sangat, bermanfaat, sekali, untuk, saya, belajar, terimakasih, ruangguru]","[ruangguru, bermanfaat, belajar, terimakasih, ruangguru]",ruangguru bermanfaat belajar terimakasih ruangguru,13,positive

In [13]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['label'] = encoder.fit_transform(df['polarity'])

In [14]:
df

,content,text_clean,text_casefoldingText,text_slangwords,text_tokenizingText,text_stopword,text_akhir,polarity_score,polarity,label
0,semuanya yg ada di ruang guru sangat bagus tetapi ketika Saya mau mengerjakan drill soal selalu saja soalnya tidak bisa di geser sudah di coba berulang kali tetap gak bisa . Tolong dong di perbaiki sistem nya masa cuma chat wa aja yg cepat tetapi sistem nya tidak dapat cepat bekerja.,semuanya yg ada di ruang guru sangat bagus tetapi ketika Saya mau mengerjakan drill soal selalu saja soalnya tidak bisa di geser sudah di coba berulang kali tetap gak bisa Tolong dong di perbaiki sistem nya masa cuma chat wa aja yg cepat tetapi sistem nya tidak dapat cepat bekerja,semuanya yg ada di ruang guru sangat bagus tetapi ketika saya mau mengerjakan drill soal selalu saja soalnya tidak bisa di geser sudah di coba berulang kali tetap gak bisa tolong dong di perbaiki sistem nya masa cuma chat wa aja yg cepat tetapi sistem nya tidak dapat cepat bekerja,semuanya yang ada di ruang guru sangat bagus tetapi ketika saya mau mengerjakan drill soal selalu saja soalnya tidak bisa di geser sudah di coba berulang kali tetap gak bisa tolong dong di perbaiki sistem nya masa cuma chat wa saja yang cepat tetapi sistem nya tidak dapat cepat bekerja,"[semuanya, yang, ada, di, ruang, guru, sangat, bagus, tetapi, ketika, saya, mau, mengerjakan, drill, soal, selalu, saja, soalnya, tidak, bisa, di, geser, sudah, di, coba, berulang, kali, tetap, gak, bisa, tolong, dong, di, perbaiki, sistem, nya, masa, cuma, chat, wa, saja, yang, cepat, tetapi, sistem, nya, tidak, dapat, cepat, bekerja]","[ruang, guru, bagus, drill, geser, coba, berulang, kali, tolong, perbaiki, sistem, chat, wa, cepat, sistem, cepat]",ruang guru bagus drill geser coba berulang kali tolong perbaiki sistem chat wa cepat sistem cepat,-9,negative,0
1,"saya lagi nonton video pembelajaran nih, dimana video pembelajarannnya akan berakhir ±1 menit kemudian. Sedangkan saya posisinya masih mengerjakan soal dari latihan soal yang ada dalam video. Belum rampung saya menjawab, itu tiba tiba keluar notifikasi untuk lanjut ke fitur kuis. Untuk lanjut ke fitur kuisnya kan dihitung mundur, tapi bisa dibatalkan. Namun, saat dibatalkan, opsi fiturnyakan masih ada di videonya. Nah itu menggangu untuk saya menjawab soal, karena opsinya menutupi jawaban",saya lagi nonton video pembelajaran nih dimana video pembelajarannnya akan berakhir menit kemudian Sedangkan saya posisinya masih mengerjakan soal dari latihan soal yang ada dalam video Belum rampung saya menjawab itu tiba tiba keluar notifikasi untuk lanjut ke fitur kuis Untuk lanjut ke fitur kuisnya kan dihitung mundur tapi bisa dibatalkan Namun saat dibatalkan opsi fiturnyakan masih ada di videonya Nah itu menggangu untuk saya menjawab soal karena opsinya menutupi jawaban,saya lagi nonton video pembelajaran nih dimana video pembelajarannnya akan berakhir menit kemudian sedangkan saya posisinya masih mengerjakan soal dari latihan soal yang ada dalam video belum rampung saya menjawab itu tiba tiba keluar notifikasi untuk lanjut ke fitur kuis untuk lanjut ke fitur kuisnya kan dihitung mundur tapi bisa dibatalkan namun saat dibatalkan opsi fiturnyakan masih ada di videonya nah itu menggangu untuk saya menjawab soal karena opsinya menutupi jawaban,saya lagi nonton video pembelajaran ini dimana video pembelajarannnya akan berakhir menit kemudian sedangkan saya posisinya masih mengerjakan soal dari latihan soal yang ada dalam video belum rampung saya menjawab itu tiba tiba keluar notifikasi untuk lanjut ke fitur kuis untuk lanjut ke fitur kuisnya kan dihitung mundur tapi bisa dibatalkan namun saat dibatalkan opsi fiturnyakan masih ada di videonya nah itu menggangu untuk saya menjawab soal karena opsinya menutupi jawaban,"[saya, lagi, nonton, video, pembelajaran, ini, dimana, video, pembelajarannnya, akan, berakhir, menit, kemudian, sedangkan, saya, posisinya, masih, mengerjakan, soal, dari, latihan, soal, yang, ada, dalam, video, belum, rampung, saya, menjawab, itu, tiba, tiba, keluar, notifikasi, untuk, lanjut, ke, fitur, kuis, untuk, lanjut, ke, fitur, kuisnya, kan, dihitung, mundur, tapi, bisa, dibatalkan, namun, saat, dibatalkan, opsi, fiturnyakan, masih, ada, di, videonya, nah, itu, menggangu, untuk, saya, menjawab, soal, karena, opsinya, menutupi, jawaban]","[nonton, video, pembelajaran, dimana, video, pembelajarannnya, menit, posisinya, latihan, video, rampung, notifikasi, fitur, kuis, fitur, kuisnya, dihitung, mundur, dibatalkan, dibatalkan, opsi, fiturnyakan, videonya, menggangu, opsinya, menutupi]",nonton video pembelajaran dimana video pembelajarannnya menit posisinya latihan video rampung notifikasi fitur kuis fitur kuisnya dihitung mundur dibatalkan dibatalkan opsi fiturnyakan videonya menggangu opsinya menutupi,1,positive,1
2,"bagus banget nih buat belajar, untuk sekarang aku masih kadang²liat vid pembelajaran di RUANG GURU, bisa di sesuaikan juga untuk kelas berapa nya, jadi kalo liat vid pembelajaran, sesuai sama materi yang ada di sekolah 🏫, ini juga untuk persiapan buat kelas 8 supaya aku bisa lebih ningkatin skill belajar aku untuk dapetin nilai yang bagus, sekaligus biar bisa lebih paham untuk memahami materi di sekolah, aku download apk ini karena aku mau ngalahin temen aku supaya aku bisa rebut rank ke 2 🤭",bagus banget nih buat belajar untuk sekarang aku masih kadang²liat vid pembelajaran di RUANG GURU bisa di sesuaikan juga untuk kelas berapa nya jadi kalo liat vid pembelajaran sesuai sama materi yang ada di sekolah ini juga untuk persiapan buat kelas supaya aku bisa lebih ningkatin skill belajar aku untuk dapetin nilai yang bagus sekaligus biar bisa lebih paham untuk memahami materi di sekolah aku download apk ini karena aku mau ngalahin temen aku supaya aku bisa rebut rank ke,bagus banget nih buat belajar untuk sekarang aku masih kadang²liat vid pembelajaran di ruang guru bisa di sesuaikan juga untuk kelas berapa nya jadi kalo liat vid pembelajaran sesuai sama materi yang ada di sekolah ini juga untuk persiapan buat kelas supaya aku bisa lebih ningkatin skill belajar aku untuk dapetin nilai yang bagus sekaligus biar bisa lebih paham untuk memahami materi di sekolah aku download apk ini karena aku mau ngalahin temen aku supaya aku bisa rebut rank ke,bagus banget ini buat belajar untuk sekarang aku masih kadang²liat vid pembelajaran di ruang guru bisa di sesuaikan juga untuk kelas berapa nya jadi kalau lihat vid pembelajaran sesuai sama materi yang ada di sekolah ini juga untuk persiapan buat kelas supaya aku bisa lebih ningkatin skill belajar aku untuk dapetin nilai yang bagus sekaligus biar bisa lebih paham untuk memahami materi di sekolah aku download apk ini karena aku mau ngalahin teman aku supaya aku bisa rebut rank ke,"[bagus, banget, ini, buat, belajar, untuk, sekarang, aku, masih, kadang²liat, vid, pembelajaran, di, ruang, guru, bisa, di, sesuaikan, juga, untuk, kelas, berapa, nya, jadi, kalau, lihat, vid, pembelajaran, sesuai, sama, materi, yang, ada, di, sekolah, ini, juga, untuk, persiapan, buat, kelas, supaya, aku, bisa, lebih, ningkatin, skill, belajar, aku, untuk, dapetin, nilai, yang, bagus, sekaligus, biar, bisa, lebih, paham, untuk, memahami, materi, di, sekolah, aku, download, apk, ini, karena, aku, mau, ngalahin, teman, aku, supaya, aku, bisa, rebut, rank, ke]","[bagus, banget, belajar, kadang²liat, vid, pembelajaran, ruang, guru, sesuaikan, kelas, lihat, vid, pembelajaran, sesuai, materi, sekolah, persiapan, kelas, ningkatin, skill, belajar, dapetin, nilai, bagus, biar, paham, memahami, materi, sekolah, download, apk, ngalahin, teman, rebut, rank]",bagus banget belajar kadang²liat vid pembelajaran ruang guru sesuaikan kelas lihat vid pembelajaran sesuai materi sekolah persiapan kelas ningkatin skill belajar dapetin nilai bagus biar paham memahami materi sekolah download apk ngalahin teman rebut rank,15,positive,1
3,"Overall semuanya tampak bagus, tapi tolong developer Tambahkan mode gelap dan tampilan aplikasi bisa jadi landscape, dan widget ruangguru itu bisa mirip aplikasi bahasa burung ijo sebelah. Semoga bisa improve setelahnya. Good job squad",Overall semuanya tampak bagus tapi tolong developer Tambahkan mode gelap dan tampilan aplikasi bisa jadi landscape dan widget ruangguru itu bisa mirip aplikasi bahasa burung ijo sebelah Semoga bisa improve setelahnya Good job squad,overall semuanya tampak bagus tapi tolong developer tambahkan mode gelap dan tampilan aplikasi bisa jadi landscape dan widget ruangguru itu bisa mirip aplikasi bahasa burung ijo sebelah semoga bisa improve setelahnya good job squad,overall semuanya tampak bagus tapi tolong developer tambahkan mode gelap dan tampilan aplikasi bisa jadi landscape dan widget ruangguru itu bisa mirip aplikasi bahasa burung ijo sebelah semoga bisa improve setelahnya good job squad,"[overall, semuanya, tampak, bagus, tapi, tolong, developer, tambahkan, mode, gelap, dan, tampilan, aplikasi, bisa, jadi, landscape, dan, widget, ruangguru, itu, bisa, mirip, aplikasi, bahasa, burung, ijo, sebelah, semoga, bisa, improve, setelahnya, good, job, squad]","[overall, bagus, tolong, developer, tambahkan, mode, gelap, tampilan, aplikasi, landscape, widget, ruangguru, aplikasi, bahasa, burung, ijo, sebelah, semoga, improve, setelahnya, good, job, squad]",overall bagus tolong developer tambahkan mode gelap tampilan aplikasi landscape widget ruangguru aplikasi bahasa burung ijo sebelah semoga improve setelahnya good job squad,-15,negative,0
4,"ruangguru benar² menjadi ruang yang menyenangkan untuk belajar, materinya lengkap, pengajar²nya kompeten dan ditambah ada filter adapto yang memudahkan untuk memahami pelajaran, terima kasih ruangguru telah hadir.....",ruangguru benar² menjadi ruang yang menyenangkan untuk belajar materinya lengkap pengajar²nya kompeten dan ditambah ada filter adapto yang memudahkan untuk memahami pelajaran terima kasih ruangguru telah hadir,ruangguru benar² menjadi ruang yang menyenangkan untuk belajar materinya lengkap pengajar²nya kompeten dan ditambah ada filter adapto yang memudahkan untuk memahami pelajaran terima kasih ruangguru telah hadir,ruangguru benar² menjadi ruang yang menyenangkan untuk belajar materinya lengkap pengajar²nya kompeten dan ditambah ada filter adapto yang memudahkan untuk memahami pelajaran terima kasih ruangguru telah hadir,"[ruangguru, benar², menjadi, ruang, yang, menyenangkan, untuk, belajar, materinya, lengkap, pengajar²nya, kompeten, dan, ditambah, ada, filter, adapto, yang, memudahkan, untuk, memahami, pelajaran, terima, kasih, ruangguru, telah, hadir]","[ruangguru, benar², ruang, menyenangkan, belajar, materinya, lengkap, pengajar²nya, kompeten, ditambah, filter, adapto, memudahkan, memahami, pelajaran, terima, kasih, ruangguru, hadir]",ruangguru benar² ruang menyenangkan belajar materinya lengkap pengajar²nya kompeten ditambah filter adapto memudahkan memahami pelajaran terima kasih ruangguru hadir,9,positive,1
...,...,...,...,...,...,...,...,...,...,...
21586,mendapatkan sebuah pelajaran yang lebih efektif atau lebih mudah untuk dipahami,mendapatkan sebuah pelajaran yang lebih efektif atau lebih mudah untuk dipahami,mendapatkan sebuah pelajaran yang lebih efektif atau lebih mudah untuk dipahami,mendapatkan sebuah pelajaran yang lebih efektif atau lebih mudah untuk dipahami,"[mendapatkan, sebuah, pelajaran, yang, lebih, efektif, atau, lebih, mudah, untuk, dipahami]","[pelajaran, efektif, mudah, dipahami]",pelajaran efektif mudah dipahami,10,positive,1
21587,Aplikasi ini membuat saya semakin ngerti tentang matematika dan mata pelajaran yg Lainnya,Aplikasi ini membuat saya semakin ngerti tentang matematika dan mata pelajaran yg Lainnya,aplikasi ini membuat saya semakin ngerti tentang matematika dan mata pelajaran yg lainnya,aplikasi ini membuat saya semakin mengerti tentang matematika dan mata pelajaran yang lainnya,"[aplikasi, ini, membuat, saya, semakin, mengerti, tentang, matematika, dan, mata, pelajaran, yang, lainnya]","[aplikasi, mengerti, matematika, mata, pelajaran]",aplikasi mengerti matematika mata pelajaran,-4,negative,0
21588,yey bisa belajar lagi asah otak lagi guys tapi kok susah juga ya soal2 nya 😆,yey bisa belajar lagi asah otak lagi guys tapi kok susah juga ya soal nya,yey bisa belajar lagi asah otak lagi guys tapi kok susah juga ya soal nya,yey bisa belajar lagi asah otak lagi teman-teman tapi kok susah juga iya soal nya,"[yey, bisa, belajar, lagi, asah, otak, lagi, teman-teman, tapi, kok, susah, juga, iya, soal, nya]","[yey, belajar, asah, otak, teman-teman, susah]",yey belajar asah otak teman-teman susah,-3,negative,0
21589,aplikasi ini bagus sangat ber prestasi da selamat ulang tahun Ruangguru yang ke 5😁,aplikasi ini bagus sangat ber prestasi da selamat ulang tahun Ruangguru yang ke,aplikasi ini bagus sangat ber prestasi da selamat ulang tahun ruangguru yang ke,aplikasi ini bagus sangat ber prestasi da selamat ulang tahun ruangguru yang ke,"[aplikasi, ini, bagus, sangat, ber, prestasi, da, selamat, ulang, tahun, ruangguru, yang, ke]","[aplikasi, bagus, ber, prestasi, da, selamat, ulang, ruangguru]",aplikasi bagus ber prestasi da selamat ulang ruangguru,-1,negative,0
21590,"Ruangguru sangat bermanfaat sekali untuk saya belajar, terimakasih ruangguru.",Ruangguru sangat bermanfaat sekali untuk saya belajar terimakasih ruangguru,ruangguru sangat bermanfaat sekali untuk saya belajar terimakasih ruangguru,ruangguru sangat bermanfaat sekali untuk saya belajar terimakasih ruangguru,"[ruangguru, sangat, bermanfaat, sekali, untuk, saya, belajar, terimakasih, ruangguru]","[ruangguru, bermanfaat, belajar, terimakasih, ruangguru]",ruangguru bermanfaat belajar terimakasih ruangguru,13,positive,1

# Tokenizer

In [15]:
import pandas as pd
import numpy as np
import requests, gzip, shutil, os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample
import matplotlib.pyplot as plt

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical

In [16]:
# Tokenisasi
tokenizer = Tokenizer(num_words=10000, oov_token='<OOV>')
tokenizer.fit_on_texts(df['content'])
sequences = tokenizer.texts_to_sequences(df['content'])
padded = pad_sequences(sequences, maxlen=100, padding='post', truncating='post')

In [17]:
# Download dan ekstrak FastText jika belum ada
embedding_dim = 300
embedding_path = 'cc.id.300.vec'
compressed_path = 'cc.id.300.vec.gz'
url = "https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.id.300.vec.gz"

if not os.path.exists(embedding_path):
    print("Mengunduh embedding...")
    response = requests.get(url, stream=True)
    with open(compressed_path, 'wb') as out_file:
        shutil.copyfileobj(response.raw, out_file)
    print("Mengekstrak embedding...")
    with gzip.open(compressed_path, 'rb') as f_in:
        with open(embedding_path, 'wb') as f_out:
            shutil.copyfileobj(f_in, f_out)
    os.remove(compressed_path)

In [18]:
# Load embedding
embedding_index = {}
with open(embedding_path, encoding='utf-8') as f:
    next(f)
    for line in f:
        values = line.rstrip().split(' ')
        word = values[0]
        coefs = np.asarray(values[1:], dtype='float32')
        embedding_index[word] = coefs

In [19]:
# Buat embedding matrix
word_index = tokenizer.word_index
num_words = min(10000, len(word_index) + 1)
embedding_matrix = np.zeros((num_words, embedding_dim))

for word, i in word_index.items():
    if i < num_words:
        embedding_vector = embedding_index.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector

In [20]:
# Encode label (misalnya df['label'] isinya 'positive' dan 'negative')
label_encoder = LabelEncoder()
df['label_encoded'] = label_encoder.fit_transform(df['label'])  # positive = 1, negative = 0

# Gabungkan fitur dan label untuk balancing
data = np.hstack((padded, df['label_encoded'].values.reshape(-1, 1)))

# Pisahkan berdasarkan kelas
data_pos = data[data[:, -1] == 1]
data_neg = data[data[:, -1] == 0]

# Oversample kelas minoritas
data_neg_upsampled = resample(data_neg, replace=True, n_samples=len(data_pos), random_state=42)

# Gabungkan kembali dan acak
balanced_data = np.vstack((data_pos, data_neg_upsampled))
np.random.shuffle(balanced_data)

# Pisahkan kembali fitur dan label
X_balanced = balanced_data[:, :-1]
y_balanced = balanced_data[:, -1]

# Data Splitting

In [21]:
# Split 80/20
X_train_80, X_test_20, y_train_80, y_test_20 = train_test_split(X_balanced, y_balanced, test_size=0.2, random_state=42)

# Split 70/30
X_train_70, X_test_30, y_train_70, y_test_30 = train_test_split(X_balanced, y_balanced, test_size=0.3, random_state=42)

In [28]:
print(f"Ukuran padded: {padded.shape}")
print(f"Ukuran label: {df['label'].shape}")

Ukuran padded: (21591, 100)
Ukuran label: (21591,)

# LSTM

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.layers import Bidirectional

# Hitung class weight
class_weights_80 = compute_class_weight(class_weight='balanced', classes=np.unique(y_train_80), y=y_train_80)
class_weights_dict_80 = dict(enumerate(class_weights_80))

# Model
model_80 = Sequential()
model_80.add(Embedding(input_dim=10000, output_dim=300, weights=[embedding_matrix],
                       input_length=100, trainable=False))
model_80.add(Bidirectional(LSTM(64, return_sequences=True)))
model_80.add(Dropout(0.3))
model_80.add(Bidirectional(LSTM(32)))
model_80.add(Dense(32, activation='relu'))
model_80.add(Dense(1, activation='sigmoid'))

# Compile
optimizer = Adam(learning_rate=0.0005)
model_80.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

# Train
history_80 = model_80.fit(X_train_80, y_train_80,
                          validation_data=(X_test_20, y_test_20),
                          epochs=10, batch_size=32,
                          class_weight=class_weights_dict_80)

# Evaluasi
loss_80, acc_80 = model_80.evaluate(X_test_20, y_test_20, verbose=0)
print(f"Akurasi model (80/20): {acc_80 * 100:.2f}%")111111

c:\Users\USER\anaconda3\envs\sentimenvenv\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Epoch 1/10
788/788 ━━━━━━━━━━━━━━━━━━━━ 149s 179ms/step - accuracy: 0.6535 - loss: 0.6209 - val_accuracy: 0.7566 - val_loss: 0.5060
Epoch 2/10
788/788 ━━━━━━━━━━━━━━━━━━━━ 148s 187ms/step - accuracy: 0.7628 - loss: 0.4990 - val_accuracy: 0.7803 - val_loss: 0.4761
Epoch 3/10
788/788 ━━━━━━━━━━━━━━━━━━━━ 133s 169ms/step - accuracy: 0.7807 - loss: 0.4684 - val_accuracy: 0.7780 - val_loss: 0.4730
Epoch 4/10
788/788 ━━━━━━━━━━━━━━━━━━━━ 133s 169ms/step - accuracy: 0.8002 - loss: 0.4364 - val_accuracy: 0.8028 - val_loss: 0.4304
Epoch 5/10
788/788 ━━━━━━━━━━━━━━━━━━━━ 162s 194ms/step - accuracy: 0.8109 - loss: 0.4204 - val_accuracy: 0.8050 - val_loss: 0.4248
Epoch 6/10
788/788 ━━━━━━━━━━━━━━━━━━━━ 140s 177ms/step - accuracy: 0.8266 - loss: 0.3854 - val_accuracy: 0.8101 - val_loss: 0.4135
Epoch 7/10
788/788 ━━━━━━━━━━━━━━━━━━━━ 141s 179ms/step - accuracy: 0.8337 - loss: 0.3747 - val_accuracy: 0.8198 - val_loss: 0.4005
Epoch 8/10
788/788 ━━━━━━━━━━━━━━━━━━━━ 134s 170ms/step - accuracy: 0.8429 - loss: 0.3582 - val_accuracy: 0.8207 - val_loss: 0.3986
Epoch 9/10
788/788 ━━━━━━━━━━━━━━━━━━━━ 137s 164ms/step - accuracy: 0.8548 - loss: 0.3380 - val_accuracy: 0.8053 - val_loss: 0.4205
Epoch 10/10
788/788 ━━━━━━━━━━━━━━━━━━━━ 138s 176ms/step - accuracy: 0.8700 - loss: 0.3153 - val_accuracy: 0.8372 - val_loss: 0.3815
Akurasi model (80/20): 83.72%

In [33]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.optimizers import Adam

class_weights_70 = compute_class_weight(class_weight='balanced', classes=np.unique(y_train_70), y=y_train_70)
class_weights_dict_70 = dict(enumerate(class_weights_70))

# Model untuk 70/30
model_70 = Sequential()
model_70.add(Embedding(input_dim=10000, output_dim=300, weights=[embedding_matrix],
                       input_length=100, trainable=False))
model_70.add(Bidirectional(LSTM(64, return_sequences=True)))
model_70.add(Dropout(0.3))
model_70.add(Bidirectional(LSTM(32)))
model_70.add(Dense(32, activation='relu'))
model_70.add(Dense(1, activation='sigmoid'))

optimizer = Adam(learning_rate=0.0005)

model_70.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

# Melatih model untuk data 70/30
history_70 = model_70.fit(X_train_70, y_train_70,
                          validation_data=(X_test_30, y_test_30),
                          epochs=10, batch_size=32,
                          class_weight=class_weights_dict_70)

# Evaluasi model
score_70 = model_70.evaluate(X_test_30, y_test_30, verbose=0)
print(f"Akurasi Model LSTM (70/30): {score_70[1] * 100:.2f}%")

c:\Users\USER\anaconda3\envs\sentimenvenv\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Epoch 1/10
690/690 ━━━━━━━━━━━━━━━━━━━━ 151s 202ms/step - accuracy: 0.6609 - loss: 0.6167 - val_accuracy: 0.7645 - val_loss: 0.5016
Epoch 2/10
690/690 ━━━━━━━━━━━━━━━━━━━━ 125s 181ms/step - accuracy: 0.7558 - loss: 0.5096 - val_accuracy: 0.7799 - val_loss: 0.4777
Epoch 3/10
690/690 ━━━━━━━━━━━━━━━━━━━━ 130s 188ms/step - accuracy: 0.7718 - loss: 0.4868 - val_accuracy: 0.7509 - val_loss: 0.4971
Epoch 4/10
690/690 ━━━━━━━━━━━━━━━━━━━━ 127s 183ms/step - accuracy: 0.7962 - loss: 0.4424 - val_accuracy: 0.7879 - val_loss: 0.4559
Epoch 5/10
690/690 ━━━━━━━━━━━━━━━━━━━━ 124s 180ms/step - accuracy: 0.7958 - loss: 0.4392 - val_accuracy: 0.8023 - val_loss: 0.4349
Epoch 6/10
690/690 ━━━━━━━━━━━━━━━━━━━━ 125s 181ms/step - accuracy: 0.8113 - loss: 0.4138 - val_accuracy: 0.8085 - val_loss: 0.4252
Epoch 7/10
690/690 ━━━━━━━━━━━━━━━━━━━━ 140s 178ms/step - accuracy: 0.8256 - loss: 0.3888 - val_accuracy: 0.8160 - val_loss: 0.4120
Epoch 8/10
690/690 ━━━━━━━━━━━━━━━━━━━━ 144s 181ms/step - accuracy: 0.8366 - loss: 0.3733 - val_accuracy: 0.8008 - val_loss: 0.4299
Epoch 9/10
690/690 ━━━━━━━━━━━━━━━━━━━━ 121s 175ms/step - accuracy: 0.8433 - loss: 0.3590 - val_accuracy: 0.8206 - val_loss: 0.4001
Epoch 10/10
690/690 ━━━━━━━━━━━━━━━━━━━━ 142s 174ms/step - accuracy: 0.8458 - loss: 0.3510 - val_accuracy: 0.8373 - val_loss: 0.3873
Akurasi Model LSTM (70/30): 83.73%

In [ ]:
# from keras.models import Sequential
# from keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
# from keras.optimizers import Adam

# maxlen = 100
# model = Sequential()
# model.add(Embedding(input_dim=10000, output_dim=300, weights=[embedding_matrix],
#                     input_length=maxlen, trainable=False))
# model.add(Bidirectional(LSTM(64, return_sequences=True)))
# model.add(Dropout(0.3))
# model.add(Bidirectional(LSTM(32)))
# model.add(Dense(32, activation='relu'))
# model.add(Dense(1, activation='sigmoid'))

# optimizer = Adam(learning_rate=0.0005)  # lebih kecil dari default

# model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

# from sklearn.utils.class_weight import compute_class_weight

# class_weights = compute_class_weight('balanced', classes=np.unique(y_train), y=y_train)
# class_weights_dict = dict(enumerate(class_weights))

# history = model.fit(X_train, y_train, validation_data=(X_test, y_test),
#                     epochs=10, batch_size=32)

Epoch 1/10
540/540 ━━━━━━━━━━━━━━━━━━━━ 189s 334ms/step - accuracy: 0.7381 - loss: 0.5496 - val_accuracy: 0.7560 - val_loss: 0.4860
Epoch 2/10
540/540 ━━━━━━━━━━━━━━━━━━━━ 176s 327ms/step - accuracy: 0.7787 - loss: 0.4574 - val_accuracy: 0.7840 - val_loss: 0.4488
Epoch 3/10
540/540 ━━━━━━━━━━━━━━━━━━━━ 178s 329ms/step - accuracy: 0.7957 - loss: 0.4278 - val_accuracy: 0.7979 - val_loss: 0.4364
Epoch 4/10
540/540 ━━━━━━━━━━━━━━━━━━━━ 180s 334ms/step - accuracy: 0.8099 - loss: 0.4112 - val_accuracy: 0.7979 - val_loss: 0.4263
Epoch 5/10
540/540 ━━━━━━━━━━━━━━━━━━━━ 195s 321ms/step - accuracy: 0.8173 - loss: 0.3933 - val_accuracy: 0.8060 - val_loss: 0.4101
Epoch 6/10
540/540 ━━━━━━━━━━━━━━━━━━━━ 179s 331ms/step - accuracy: 0.8252 - loss: 0.3831 - val_accuracy: 0.8074 - val_loss: 0.4121
Epoch 7/10
540/540 ━━━━━━━━━━━━━━━━━━━━ 196s 321ms/step - accuracy: 0.8300 - loss: 0.3745 - val_accuracy: 0.8002 - val_loss: 0.4405
Epoch 8/10
540/540 ━━━━━━━━━━━━━━━━━━━━ 200s 318ms/step - accuracy: 0.8359 - loss: 0.3665 - val_accuracy: 0.8152 - val_loss: 0.4051
Epoch 9/10
540/540 ━━━━━━━━━━━━━━━━━━━━ 169s 313ms/step - accuracy: 0.8400 - loss: 0.3525 - val_accuracy: 0.8213 - val_loss: 0.3930
Epoch 10/10
540/540 ━━━━━━━━━━━━━━━━━━━━ 211s 330ms/step - accuracy: 0.8526 - loss: 0.3450 - val_accuracy: 0.8240 - val_loss: 0.3878

In [ ]:
# # Evaluasi model
# loss, accuracy = model.evaluate(X_test, y_test)
# print(f"Akurasi model: {accuracy * 100:.2f}%")

135/135 ━━━━━━━━━━━━━━━━━━━━ 17s 125ms/step - accuracy: 0.8258 - loss: 0.3859
Akurasi model: 82.40%

In [ ]:
# from keras.models import Sequential
# from keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
# from keras.optimizers import Adam
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(padded, df['label'], test_size=0.2, random_state=42)

# combinations = [
#     {'lstm_units': 64, 'dropout': 0.3, 'lr': 0.001},
#     {'lstm_units': 64, 'dropout': 0.5, 'lr': 0.001},
#     {'lstm_units': 128, 'dropout': 0.3, 'lr': 0.001},
#     {'lstm_units': 128, 'dropout': 0.5, 'lr': 0.001},
#     {'lstm_units': 64, 'dropout': 0.3, 'lr': 0.0005},
#     {'lstm_units': 128, 'dropout': 0.3, 'lr': 0.0005},
# ]

# results = []

# for config in combinations:
#     print(f"Training with LSTM={config['lstm_units']}, Dropout={config['dropout']}, LR={config['lr']}")
    
#     model = Sequential()
#     model.add(Embedding(input_dim=10000, output_dim=300, weights=[embedding_matrix],
#                         input_length=maxlen, trainable=False))
#     model.add(Bidirectional(LSTM(config['lstm_units'], return_sequences=True)))
#     model.add(Dropout(config['dropout']))
#     model.add(Bidirectional(LSTM(config['lstm_units'])))
#     model.add(Dense(1, activation='sigmoid'))

#     optimizer = Adam(learning_rate=config['lr'])
#     model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

#     history = model.fit(X_train, y_train, validation_data=(X_test, y_test),
#                         epochs=5, batch_size=16, verbose=0)

#     acc = history.history['val_accuracy'][-1] * 100
#     print(f"Validation Accuracy: {acc:.2f}%\n")
#     results.append((config, acc))

# # Menampilkan kombinasi terbaik
# best = max(results, key=lambda x: x[1])
# print("Kombinasi terbaik:")
# print(f"LSTM Units: {best[0]['lstm_units']}, Dropout: {best[0]['dropout']}, Learning Rate: {best[0]['lr']}")
# print(f"Validation Accuracy: {best[1]:.2f}%")

Training with LSTM=64, Dropout=0.3, LR=0.001
Validation Accuracy: 80.11%

Training with LSTM=64, Dropout=0.5, LR=0.001
Validation Accuracy: 83.21%

Training with LSTM=128, Dropout=0.3, LR=0.001
Validation Accuracy: 81.06%

Training with LSTM=128, Dropout=0.5, LR=0.001
Validation Accuracy: 83.56%

Training with LSTM=64, Dropout=0.3, LR=0.0005
Validation Accuracy: 80.16%

Training with LSTM=128, Dropout=0.3, LR=0.0005
Validation Accuracy: 80.62%

Kombinasi terbaik:
LSTM Units: 128, Dropout: 0.5, Learning Rate: 0.001
Validation Accuracy: 83.56%

# CNN

In [34]:
from keras.models import Sequential
from keras.layers import Embedding, Conv1D, MaxPooling1D, Dense, Dropout, Flatten
from keras.optimizers import Adam
from sklearn.utils.class_weight import compute_class_weight

# Hitung class weight untuk 80/20
class_weights_80 = compute_class_weight('balanced', classes=np.unique(y_train_80), y=y_train_80)
class_weights_dict_80 = dict(enumerate(class_weights_80))

# Model CNN 80/20
model_cnn_80 = Sequential()
model_cnn_80.add(Embedding(input_dim=10000, output_dim=300, weights=[embedding_matrix], input_length=100, trainable=False))
model_cnn_80.add(Conv1D(128, 5, activation='relu'))
model_cnn_80.add(MaxPooling1D(pool_size=4))
model_cnn_80.add(Flatten())
model_cnn_80.add(Dense(64, activation='relu'))
model_cnn_80.add(Dropout(0.5))
model_cnn_80.add(Dense(1, activation='sigmoid'))

model_cnn_80.compile(loss='binary_crossentropy', optimizer=Adam(), metrics=['accuracy'])

# Latih model CNN 80/20
history_cnn_80 = model_cnn_80.fit(X_train_80, y_train_80,
                                  validation_data=(X_test_20, y_test_20),
                                  epochs=10, batch_size=64,
                                  class_weight=class_weights_dict_80)

# Evaluasi
score_cnn_80 = model_cnn_80.evaluate(X_test_20, y_test_20, verbose=0)
print(f"CNN Model Accuracy (80/20): {score_cnn_80[1] * 100:.2f}%")

c:\Users\USER\anaconda3\envs\sentimenvenv\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Epoch 1/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 36s 86ms/step - accuracy: 0.6475 - loss: 0.6181 - val_accuracy: 0.8033 - val_loss: 0.4415
Epoch 2/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.8322 - loss: 0.3930 - val_accuracy: 0.8559 - val_loss: 0.3545
Epoch 3/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 34s 85ms/step - accuracy: 0.9070 - loss: 0.2480 - val_accuracy: 0.8809 - val_loss: 0.3073
Epoch 4/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 34s 87ms/step - accuracy: 0.9501 - loss: 0.1439 - val_accuracy: 0.8921 - val_loss: 0.3069
Epoch 5/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 34s 86ms/step - accuracy: 0.9712 - loss: 0.0885 - val_accuracy: 0.8937 - val_loss: 0.3447
Epoch 6/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 40s 84ms/step - accuracy: 0.9817 - loss: 0.0571 - val_accuracy: 0.8812 - val_loss: 0.4459
Epoch 7/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 35s 88ms/step - accuracy: 0.9856 - loss: 0.0457 - val_accuracy: 0.8991 - val_loss: 0.4209
Epoch 8/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 35s 88ms/step - accuracy: 0.9898 - loss: 0.0331 - val_accuracy: 0.9045 - val_loss: 0.3991
Epoch 9/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 35s 89ms/step - accuracy: 0.9911 - loss: 0.0281 - val_accuracy: 0.8858 - val_loss: 0.4224
Epoch 10/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 37s 94ms/step - accuracy: 0.9861 - loss: 0.0419 - val_accuracy: 0.9139 - val_loss: 0.3943
CNN Model Accuracy (80/20): 91.39%

In [35]:
# Hitung class weight untuk 70/30
class_weights_70 = compute_class_weight('balanced', classes=np.unique(y_train_70), y=y_train_70)
class_weights_dict_70 = dict(enumerate(class_weights_70))

# Model CNN 70/30
model_cnn_70 = Sequential()
model_cnn_70.add(Embedding(input_dim=10000, output_dim=300, weights=[embedding_matrix], input_length=100, trainable=False))
model_cnn_70.add(Conv1D(128, 5, activation='relu'))
model_cnn_70.add(MaxPooling1D(pool_size=4))
model_cnn_70.add(Flatten())
model_cnn_70.add(Dense(64, activation='relu'))
model_cnn_70.add(Dropout(0.5))
model_cnn_70.add(Dense(1, activation='sigmoid'))

model_cnn_70.compile(loss='binary_crossentropy', optimizer=Adam(), metrics=['accuracy'])

# Latih model CNN 70/30
history_cnn_70 = model_cnn_70.fit(X_train_70, y_train_70,
                                  validation_data=(X_test_30, y_test_30),
                                  epochs=10, batch_size=64,
                                  class_weight=class_weights_dict_70)

# Evaluasi
score_cnn_70 = model_cnn_70.evaluate(X_test_30, y_test_30, verbose=0)
print(f"CNN Model Accuracy (70/30): {score_cnn_70[1] * 100:.2f}%")

Epoch 1/10

c:\Users\USER\anaconda3\envs\sentimenvenv\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

345/345 ━━━━━━━━━━━━━━━━━━━━ 31s 84ms/step - accuracy: 0.6315 - loss: 0.6325 - val_accuracy: 0.7937 - val_loss: 0.4592
Epoch 2/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 42s 85ms/step - accuracy: 0.8157 - loss: 0.4154 - val_accuracy: 0.8371 - val_loss: 0.3732
Epoch 3/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 41s 85ms/step - accuracy: 0.8989 - loss: 0.2644 - val_accuracy: 0.8610 - val_loss: 0.3362
Epoch 4/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 31s 90ms/step - accuracy: 0.9452 - loss: 0.1573 - val_accuracy: 0.8866 - val_loss: 0.3095
Epoch 5/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 31s 90ms/step - accuracy: 0.9674 - loss: 0.0997 - val_accuracy: 0.8875 - val_loss: 0.3357
Epoch 6/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 32s 91ms/step - accuracy: 0.9823 - loss: 0.0604 - val_accuracy: 0.9008 - val_loss: 0.3598
Epoch 7/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 33s 94ms/step - accuracy: 0.9877 - loss: 0.0430 - val_accuracy: 0.8970 - val_loss: 0.4050
Epoch 8/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 39s 87ms/step - accuracy: 0.9847 - loss: 0.0464 - val_accuracy: 0.8907 - val_loss: 0.4360
Epoch 9/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 33s 95ms/step - accuracy: 0.9936 - loss: 0.0237 - val_accuracy: 0.8892 - val_loss: 0.4476
Epoch 10/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 34s 99ms/step - accuracy: 0.9914 - loss: 0.0274 - val_accuracy: 0.8824 - val_loss: 0.5293
CNN Model Accuracy (70/30): 88.24%

# GRU

In [36]:
from keras.models import Sequential
from keras.layers import Embedding, GRU, Dense, Dropout, GlobalMaxPooling1D
from keras.optimizers import Adam
from sklearn.utils.class_weight import compute_class_weight

# Hitung class weight 80/20
class_weights_80 = compute_class_weight('balanced', classes=np.unique(y_train_80), y=y_train_80)
class_weights_dict_80 = dict(enumerate(class_weights_80))

# Model GRU 80/20
model_gru_80 = Sequential()
model_gru_80.add(Embedding(input_dim=10000, output_dim=300, weights=[embedding_matrix], input_length=100, trainable=False))
model_gru_80.add(GRU(64, return_sequences=True))
model_gru_80.add(GlobalMaxPooling1D())
model_gru_80.add(Dense(64, activation='relu'))
model_gru_80.add(Dropout(0.5))
model_gru_80.add(Dense(1, activation='sigmoid'))

model_gru_80.compile(loss='binary_crossentropy', optimizer=Adam(), metrics=['accuracy'])

# Latih model GRU 80/20
history_gru_80 = model_gru_80.fit(X_train_80, y_train_80,
                                  validation_data=(X_test_20, y_test_20),
                                  epochs=10, batch_size=64,
                                  class_weight=class_weights_dict_80)

# Evaluasi model GRU 80/20
score_gru_80 = model_gru_80.evaluate(X_test_20, y_test_20, verbose=0)
print(f'GRU Model Accuracy (80/20): {score_gru_80[1] * 100:.2f}%')

Epoch 1/10

c:\Users\USER\anaconda3\envs\sentimenvenv\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

394/394 ━━━━━━━━━━━━━━━━━━━━ 40s 94ms/step - accuracy: 0.6222 - loss: 0.6410 - val_accuracy: 0.7503 - val_loss: 0.5190
Epoch 2/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 37s 94ms/step - accuracy: 0.7685 - loss: 0.4956 - val_accuracy: 0.7944 - val_loss: 0.4497
Epoch 3/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 37s 93ms/step - accuracy: 0.8034 - loss: 0.4300 - val_accuracy: 0.8285 - val_loss: 0.3929
Epoch 4/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 37s 94ms/step - accuracy: 0.8375 - loss: 0.3750 - val_accuracy: 0.8406 - val_loss: 0.3687
Epoch 5/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 36s 92ms/step - accuracy: 0.8662 - loss: 0.3335 - val_accuracy: 0.8575 - val_loss: 0.3363
Epoch 6/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 48s 121ms/step - accuracy: 0.8828 - loss: 0.2965 - val_accuracy: 0.8583 - val_loss: 0.3470
Epoch 7/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 70s 92ms/step - accuracy: 0.8976 - loss: 0.2650 - val_accuracy: 0.8769 - val_loss: 0.3069
Epoch 8/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 38s 96ms/step - accuracy: 0.9128 - loss: 0.2284 - val_accuracy: 0.8769 - val_loss: 0.2939
Epoch 9/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 37s 94ms/step - accuracy: 0.9292 - loss: 0.1952 - val_accuracy: 0.8886 - val_loss: 0.2940
Epoch 10/10
394/394 ━━━━━━━━━━━━━━━━━━━━ 37s 95ms/step - accuracy: 0.9397 - loss: 0.1661 - val_accuracy: 0.8948 - val_loss: 0.2781
GRU Model Accuracy (80/20): 89.48%

In [37]:
# Hitung class weight 70/30
class_weights_70 = compute_class_weight('balanced', classes=np.unique(y_train_70), y=y_train_70)
class_weights_dict_70 = dict(enumerate(class_weights_70))

# Model GRU 70/30
model_gru_70 = Sequential()
model_gru_70.add(Embedding(input_dim=10000, output_dim=300, weights=[embedding_matrix], input_length=100, trainable=False))
model_gru_70.add(GRU(64, return_sequences=True))
model_gru_70.add(GlobalMaxPooling1D())
model_gru_70.add(Dense(64, activation='relu'))
model_gru_70.add(Dropout(0.5))
model_gru_70.add(Dense(1, activation='sigmoid'))

model_gru_70.compile(loss='binary_crossentropy', optimizer=Adam(), metrics=['accuracy'])

# Latih model GRU 70/30
history_gru_70 = model_gru_70.fit(X_train_70, y_train_70,
                                  validation_data=(X_test_30, y_test_30),
                                  epochs=10, batch_size=64,
                                  class_weight=class_weights_dict_70)

# Evaluasi model GRU 70/30
score_gru_70 = model_gru_70.evaluate(X_test_30, y_test_30, verbose=0)
print(f'GRU Model Accuracy (70/30): {score_gru_70[1] * 100:.2f}%')

c:\Users\USER\anaconda3\envs\sentimenvenv\lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Epoch 1/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 39s 103ms/step - accuracy: 0.6091 - loss: 0.6508 - val_accuracy: 0.7490 - val_loss: 0.5220
Epoch 2/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 44s 128ms/step - accuracy: 0.7595 - loss: 0.5040 - val_accuracy: 0.7982 - val_loss: 0.4488
Epoch 3/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 69s 90ms/step - accuracy: 0.7994 - loss: 0.4390 - val_accuracy: 0.7894 - val_loss: 0.4471
Epoch 4/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 43s 95ms/step - accuracy: 0.8211 - loss: 0.3935 - val_accuracy: 0.8356 - val_loss: 0.3754
Epoch 5/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 33s 97ms/step - accuracy: 0.8522 - loss: 0.3484 - val_accuracy: 0.8390 - val_loss: 0.3654
Epoch 6/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 37s 108ms/step - accuracy: 0.8759 - loss: 0.3072 - val_accuracy: 0.8535 - val_loss: 0.3447
Epoch 7/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 37s 95ms/step - accuracy: 0.8956 - loss: 0.2700 - val_accuracy: 0.8718 - val_loss: 0.3174
Epoch 8/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 33s 95ms/step - accuracy: 0.9068 - loss: 0.2440 - val_accuracy: 0.8801 - val_loss: 0.3042
Epoch 9/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 33s 96ms/step - accuracy: 0.9234 - loss: 0.2118 - val_accuracy: 0.8818 - val_loss: 0.3027
Epoch 10/10
345/345 ━━━━━━━━━━━━━━━━━━━━ 41s 97ms/step - accuracy: 0.9362 - loss: 0.1795 - val_accuracy: 0.8926 - val_loss: 0.2871
GRU Model Accuracy (70/30): 89.26%

# Summary

hasil yang didapat adalah test model terbaik adalah CNN dengan pembagian 80/20, dengan akurasi 91.39%

# Inference

In [45]:
model_cnn_80.save('cnn_model_8020.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [47]:
with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)

In [51]:
import numpy as np
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences
import pickle

# ========== Load Model dan Tokenizer ==========
model = load_model('cnn_model_8020.h5')

with open('tokenizer.pkl', 'rb') as f:
    tokenizer = pickle.load(f)

MAXLEN = 100
LABELS = ['negatif', 'positif']  # 2 kelas

# ========== Fungsi Preprocessing ==========
def full_preprocessing(teks):
    teks_clean = cleaningText(teks)
    teks_casefold = casefoldingText(teks_clean)
    teks_slangfixed = fix_slangwords(teks_casefold)
    teks_tokenized = tokenizingText(teks_slangfixed)
    teks_filtered = filteringText(teks_tokenized)
    teks_final = toSentence(teks_filtered)
    return teks_final

# ========== Prediksi Sentimen ==========
def predict_sentiment(text):
    preprocessed_text = full_preprocessing(text)
    sequence = tokenizer.texts_to_sequences([preprocessed_text])
    padded = pad_sequences(sequence, maxlen=MAXLEN, padding='post', truncating='post')
    prob = model.predict(padded, verbose=0)[0][0]

    label = LABELS[1] if prob >= 0.5 else LABELS[0]
    return label, float(prob)

# ========== Inference: Input dari User ==========
if __name__ == '__main__':
    kalimat_baru = input("Masukkan kalimat baru: ")
    label, confidence = predict_sentiment(kalimat_baru)

    print(f"\nHasil Prediksi Sentimen:")
    print(f"Teks: \"{kalimat_baru}\"")
    print(f"Sentimen: {label.upper()} (Confidence: {confidence:.2f})")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

Hasil Prediksi Sentimen:
Teks: "sangat membantu"
Sentimen: POSITIF (Confidence: 0.91)